import {currentClassroomExperiment} from '../../shared/classroom-expression.mjs';
import type {PilotLesson,WidgetState} from './types';
import TeachingWidget from './TeachingDiagrams';
import './classroom.css';
import IntroVisual from './IntroVisual';
import StoryPicture from './StoryPicture';
import {TeachingDiagram} from './TeachingDiagrams';
import {withdrawnLessons,withdrawnTasks} from '../../shared/withdrawn-checks.mjs';
import {introVisuals,predictionVisuals} from '../../content/pilot/intro-visuals.mjs';

export default function ChildClassroom({lesson,widgets,change,onPractice}:{lesson:PilotLesson;widgets:Record<string,WidgetState>;change:(id:string,value:WidgetState)=>void;onPractice:()=>void}){
 const content=lesson.childClassroom!,state=widgets.classroom??{},screen=state.chapterScreen??0,visualOnly=lesson.interactionStatus==='static-visual',steps=['真实问题','先猜一猜',visualOnly?'画图想一想':'亲手实验','说出发现','写成数学','自己验证'];
 // A background server may still hold the older API payload after a frontend build.
 // Both forms use the same authored source; never let a missing field blank the class.
 const storyVisual=content.storyVisual??introVisuals[lesson.lessonId],predictionVisual=content.predictionVisual??predictionVisuals[lesson.lessonId];
 const move=(n:number)=>{change('classroom',{...state,chapterScreen:n});document.querySelector('.classroom-stage')?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};
 const experiment=lesson.articleBlocks.find(b=>b.widget)!;
 const current=currentClassroomExperiment(lesson,widgets[experiment.blockId]??{});
 const verification=withdrawnLessons.includes(lesson.lessonId)?withdrawnTasks(lesson):lesson.taskSets.core;
 const contextPicture=(prediction=false)=>{const visual=prediction?predictionVisual:storyVisual;if(visual)return <IntroVisual spec={visual} prediction={prediction}/>;return <div className="classroom-context-picture" data-intro-visual="known-conditions" data-intro-stage={prediction?'prediction':'story'}>{lesson.articleBlocks[0].diagram?<TeachingDiagram kind={lesson.articleBlocks[0].diagram} reveal={false}/>:<StoryPicture lesson={lesson}/>}</div>;};
 return <section className={`child-classroom classroom-screen-${screen}`}><nav className="classroom-route" aria-label="本课六个短步骤">{steps.map((title,i)=><button key={title} aria-current={screen===i?'step':undefined} onClick={()=>move(i)}><span>{i+1}</span><b>{title}</b></button>)}</nav>
  <div className="classroom-stage"><div className="screen-caption"><span>{screen+1} / 6</span><small>{steps[screen]}</small></div>
   {screen===0&&<div className="classroom-story"><p className="screen-kicker">今天帮 Kevin 弄明白一件事</p><h2>先看这件事</h2><p className="story-sentence">{content.story}</p>{contextPicture()}<div className="classroom-mission"><span>今天的任务</span><p>{content.mission}</p></div></div>}
   {screen===1&&<div className="classroom-predict"><h2>{content.predictQuestion}</h2><p>猜错也没关系，实验就是用来检验想法的。可以先说出来，也可以点选。</p>{contextPicture(true)}<div className="prediction-cards">{content.predictionOptions.map(option=><button key={option} aria-pressed={state.prediction===option} onClick={()=>change('classroom',{...state,prediction:option,predicted:true})}>{option}</button>)}</div><label className="optional-thought">想留一句话？（可不写）<input maxLength={180} value={state.explanation??''} placeholder="也可以指着图，口头说给家人听" onChange={e=>change('classroom',{...state,explanation:e.target.value})}/></label><button className="studio-primary" onClick={()=>{change('classroom',{...state,predicted:true,chapterScreen:2});window.scrollTo(0,0)}}>{state.prediction?(visualOnly?'带着我的猜想去看图':'带着我的猜想去实验'):(visualOnly?'我已经想过了，去看图':'我已经想过了，去实验')}</button></div>}
   {screen===2&&<><p className="experiment-mission">{content.mission}</p>{visualOnly&&<p className="saved-prediction">这节用关系图和纸笔来想。可以指一指、画一画；这里没有拖动模型。</p>}{state.prediction&&<p className="saved-prediction">刚才我的猜想：{state.prediction}</p>}{lesson.lessonId==='G3-L04-B03'&&<div className="classroom-unit-context"><h3>先看单位方纸：两个方向都分成10厘米</h3>{contextPicture()}<p>每排10小格，共10排。先口头说出单位关系，再试下面的剪角卡：剪开与移动后，覆盖量怎样变化？</p></div>}<TeachingWidget kind={experiment.widget!} scenes={lesson.mathScenes} lengthScenes={lesson.lengthScenes} conceptScenes={lesson.conceptScenes} value={widgets[experiment.blockId]??{}} onChange={s=>change(experiment.blockId,s)}/>{withdrawnLessons.includes(lesson.lessonId)&&<button className="studio-primary classroom-assessment" onClick={onPractice}>收起教具，独立做五题</button>}</>}
   {screen===3&&<div className="classroom-discover"><h2>{visualOnly?'指着刚才的图，讲讲你发现了什么':'指着刚才的实验，讲讲你发现了什么'}</h2><p className="retell-task">{content.whyQuestion??content.retell}</p><p className="prediction-comparison">{state.prediction&&<>你刚才选了“{state.prediction}”。</>}{content.observedEvidence??'指着刚才看到的变化，说给家人听。'}和你的猜想一样吗？可以口头说。</p><details><summary>需要时展开：回看开头问题的关系</summary>{content.discovery.map((text,i)=><p key={text}><span className="discovery-index">{i+1}</span>{text}</p>)}</details><details className="classroom-counterexample"><summary>想再验证一下？</summary><p>{content.counterexamplePrompt??'改变一个条件，原来的关系还成立吗？'}</p><button className="studio-ghost" onClick={()=>move(2)}>{visualOnly?'回看图找证据':'回实验找证据'}</button></details></div>}
   {screen===4&&<div className="classroom-symbols"><h2>把开头的问题翻译成数学语言</h2><p>下面对应第一步的故事。实验换过条件？再照这个方法写出你那一题的关系。</p><h3>原故事的数学表达</h3><div className="symbol-lines">{content.symbols.map(text=><p key={text}>{text}</p>)}</div>{current?<section className="current-experiment"><h3>当前实验条件</h3>{current.conditions.map(text=><p key={text}>{text}</p>)}<p className="blank-expression">{current.template}</p><p>{current.relation}空格可以口头填，也可以写在纸上，不用在这里输入。</p></section>:<p className="current-experiment-prompt">如果实验改过条件，和原故事还一样吗？指着当前的图说一说，不必写成算式。</p>}<details><summary>再看一个完整例子</summary>{lesson.articleBlocks.flatMap(b=>b.examples??[]).map(example=><div key={example.title}><h3>{example.title}</h3>{example.steps.map((step,i)=><p key={i}><strong>{step.math}</strong><br/>{step.why}</p>)}</div>)}</details></div>}
   {screen===5&&<div className="classroom-verify"><h2>{withdrawnLessons.includes(lesson.lessonId)?'收起教具，做五题':'试试这节课的巩固练习'}</h2><p className="verification-goal">{verification.length}题，一次看一道。先留首答，再用三项自查核对。</p><p>检查重点：{content.whyQuestion??content.retell}</p><details className="parent-task-preview"><summary>家长预览题组（可不看）</summary><ol>{verification.map(task=><li key={task.id}><small>{task.id}</small> {task.prompt}</li>)}</ol></details><button className="studio-primary" onClick={onPractice}>开始这组独立练习</button><p className="muted">这组可能有熟悉的巩固题，不代表全部是未见新题。后续迁移与到期复习另记证据；看完六屏只记录浏览。</p></div>}
  </div><footer className="classroom-navigation"><button className="studio-ghost" disabled={screen===0} onClick={()=>move(screen-1)}>上一步</button><span>可以随时选择任一步</span>{screen<5?<button className="studio-primary" onClick={()=>move(screen+1)}>{screen===0?'想一想':screen===1?(visualOnly?'去看图':'去实验'):screen===2?'讲出发现':screen===3?'看看数学语言':'去验证'} →</button>:<button className="studio-ghost" onClick={()=>move(2)}>{visualOnly?'再看关系图':'再做实验'}</button>}</footer>
 </section>;
}
