import {useId,useRef,useState,type DragEvent,type ReactNode} from 'react';
import {balanceState,balanceWeights,boatState,containerObjects,scaleMass,scaleObjects,stones,type HandsOnModel} from '../../../shared/hands-on-models.mjs';
import type {WidgetState} from '../types';
import {useHandsOn} from './useHandsOn';
import {useMotionValue} from '../useMotionValue';
import './hands-on.css';

function Token({label,code,onClick,disabled=false,children}:{label:string;code:string;onClick:()=>void;disabled?:boolean;children:ReactNode}){
 const drag=useRef<{x:number;y:number;moved:boolean}|null>(null),suppressClick=useRef(false),[ghost,setGhost]=useState<{x:number;y:number}|null>(null);
 const zone=code==='elephant'||code.startsWith('stone:')?'.boat-stage':code.startsWith('weight:')?'.balance-stage':'.scale-platform';
 return <button className="object-token" aria-label={label} disabled={disabled} onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,moved:false};suppressClick.current=false;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d)return;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>8)d.moved=true;if(d.moved)setGhost({x:e.clientX,y:e.clientY})}} onPointerUp={e=>{const d=drag.current;if(!d)return;if(d.moved){suppressClick.current=true;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest(zone);if(target&&target.closest('.hands-on-workbench')===e.currentTarget.closest('.hands-on-workbench'))onClick()}drag.current=null;setGhost(null);e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>{drag.current=null;setGhost(null)}} onClick={e=>{if(!suppressClick.current||e.detail===0)onClick();suppressClick.current=false}}>{children}<span>{label}</span>{ghost&&<span className="object-drag-ghost" style={{left:ghost.x+12,top:ghost.y-20}} aria-hidden="true">{children}<small>{label}</small></span>}</button>;
}
function ItemIcon({id,container=false}:{id:number;container?:boolean}){return <svg width="55" height="55" viewBox="0 0 60 60" aria-hidden="true">{container?<><path d="M15 12 L18 49 Q30 55 42 49 L45 12Z" fill={id===1?'#92cadd':'#f9f1d9'} stroke="#527eab" strokeWidth="3"/>{id!==0&&<path d="M17 29H43L41 47Q30 52 19 47Z" fill="#92cadd"/>}<ellipse cx="30" cy="12" rx="15" ry="4" fill="#fff" stroke="#527eab" strokeWidth="2"/></>:id===0?<path d="M25 40V18Q25 8 35 8Q45 8 45 18V40Q45 53 32 53Q19 53 19 40V22Q19 16 26 16Q33 16 33 22V39" fill="none" stroke="#527eab" strokeWidth="4"/>:id===1?<><path d="M30 20C8 9 4 42 20 51Q30 56 40 51C56 42 52 9 30 20" fill="#df6c4f"/><path d="M30 20Q30 6 43 8" fill="none" stroke="#469684" strokeWidth="4"/></>:id===2?<><path d="M15 12H45L49 48Q30 56 11 48Z" fill="#e9b44d" stroke="#b18b66" strokeWidth="2"/><text x="30" y="37" textAnchor="middle" fill="#735938" fontSize="14">米</text></>:<><rect x="10" y="12" width="39" height="38" rx="3" fill="#527eab"/><path d="M14 17H43M14 44H43" stroke="#fff9ef" strokeWidth="3"/><text x="30" y="36" textAnchor="middle" fill="#fff" fontSize="15">书</text></>}</svg>}
function Elephant(){return <g data-evidence="elephant"><path d="M-65-40 Q-73-76-45-82 Q-15-110 17-82 Q47-84 51-55 L64-48 Q71-33 60-13 L48-13 L47-39 L32-39 L32-9 L15-9 L13-37 L-22-37 L-22-9 L-40-9 L-43-39Z" fill="#92a7b2" stroke="#526e7a" strokeWidth="2"/><ellipse cx="23" cy="-67" rx="17" ry="22" fill="#b6c6cd"/><circle cx="43" cy="-67" r="3" fill="#253f43"/></g>}
const dropId=(event:DragEvent,prefix:string)=>{event.preventDefault();const text=event.dataTransfer.getData('text/plain');if(!new RegExp(`^${prefix}:\\d$`).test(text))return null;return Number(text.split(':')[1])};

export default function MassWorkbench({model,sceneId,value,onChange}:{model:HandsOnModel;sceneId:string;value:WidgetState;onChange:(s:WidgetState)=>void}){
 const {state,act,toolbar}=useHandsOn(model,sceneId,value,onChange),visualId=useId().replace(/:/g,'');
 const sinkFrame=useMotionValue(model.mode==='boat'?boatState(model,state).sink:0,800),angleFrame=useMotionValue(model.mode==='weigh'?balanceState(state.weights??[]).angle:0,700);
 if(model.mode==='boat'){
  const ids=state.boatStones??[],weighed=state.weighed??[],m=boatState(model,state),selected=state.weighingStone??ids[0],known=ids.filter(id=>weighed.includes(id)),allWeighed=ids.length>0&&known.length===ids.length;
  const add=(id:number)=>{if(!stones[id]||ids.includes(id))return;act('load-stone',{boatStones:[...ids,id],checked:false})};
  const board=()=>act('board-elephant',{elephant:true,checked:false});
  const mark=()=>{if(!state.elephant||ids.length||state.passenger){act('mark-waterline',{error:'先让船只载模型象。取走石块和乘员，再标记这一次的水线。'},false);return}act('mark-waterline',{waterlineMarked:true})};
  const stoneSum=known.reduce((sum,id)=>sum+stones[id].mass,0);
  return <section className="hands-on-workbench mass-workbench boat-workbench" data-model="boat"><header className="hands-heading"><span className="lab-badge">曹冲的替换实验</span><h3>象上船 → 记水线 → 用石块换回来</h3><p>这是小船和模型象的实验，质量用克记录。先称一个放不进小秤的模型象；真实大象要用更大的船和千克、吨。</p></header>
   <div className="boat-layout"><div><div className="boat-stage" data-evidence="boat" onDragOver={e=>e.preventDefault()} onDrop={e=>{const text=e.dataTransfer.getData('text/plain');if(text==='elephant'){e.preventDefault();board()}else{const id=dropId(e,'stone');if(id!==null)add(id)}}} aria-label="船舱，拖入模型象或石块">
    <svg viewBox="0 0 560 340" role="img" aria-label={`船上${state.elephant?'有模型象':'没有模型象'}，${ids.length}块石头${state.passenger?'和一名乘员':''}，${state.waterlineMarked?(m.sameWaterline?'恢复原水线':'尚未恢复原水线'):'还没有标记水线'}`}>
     <defs><pattern id={visualId+'waves'} width="70" height="18" patternUnits="userSpaceOnUse"><path d="M0 10Q18 0 35 10T70 10" fill="none" stroke="#fff" strokeOpacity=".7" strokeWidth="2"/></pattern></defs><rect x="0" y="0" width="560" height="340" fill="#f8f2df"/><path d="M0 264Q130 245 260 264T560 264V340H0Z" fill="#7ca8b1"/><path d="M0 200H560V340H0Z" fill="#92cadd" fillOpacity=".7" data-evidence="water"/><rect x="0" y="210" width="560" height="130" fill={`url(#${visualId}waves)`}/>
     <line x1="12" x2="548" y1="200" y2="200" stroke="#527eab" strokeWidth="2"/><text x="15" y="187" fill="#527eab" fontSize="14">静水水面</text>
     <g data-boat-sink={sinkFrame} transform={`translate(280 ${180+sinkFrame})`}><defs><linearGradient id={visualId+'hull'} x1="0" y1="0" x2="0" y2="1"><stop stopColor="#d4b98b"/><stop offset="1" stopColor="#815c3a"/></linearGradient></defs><ellipse cx="0" cy="-15" rx="160" ry="18" fill="#735938"/><path d="M-160-15L-135 64Q0 94 135 64L160-15Z" fill={`url(#${visualId}hull)`} stroke="#735938" strokeWidth="3"/><path d="M-160-15Q0 11 160-15" fill="none" stroke="#dfc598" strokeWidth="6"/><path d="M-138 33Q0 60 138 33M-130 51Q0 77 130 51" fill="none" stroke="#735938" strokeOpacity=".35" strokeWidth="2"/>{state.elephant&&<g transform="translate(-30 -10)" className="lab-object-arrival"><Elephant/></g>}{ids.map((id,i)=><g key={id} transform={`translate(${-110+(i%3)*65} ${-20-Math.floor(i/3)*30})`} data-evidence="replacement" className="lab-object-arrival"><path d="M-20 0L-23-16L-5-27L18-19L23-2Z" fill="#708b89" stroke="#476b66" strokeWidth="2"/><text x="0" y="-8" textAnchor="middle" fontSize="12" fill="#fff">{id+1}</text></g>)}{state.passenger&&<g transform="translate(113 -38)"><circle cy="-13" r="9" fill="#e9b44d"/><path d="M-10 25V0H10V25" fill="#df6c4f"/></g>}
      {state.waterlineMarked&&<g data-evidence="waterline"><line x1="-140" x2="140" y1={20-m.targetSink} y2={20-m.targetSink} stroke="#df6c4f" strokeWidth="4" strokeDasharray="8 5"/><text x="0" y={40-m.targetSink} textAnchor="middle" fill="#fff9ef" fontSize="14">第一次的水线标记</text></g>}
     </g><text x="280" y="316" textAnchor="middle" fill="#253f43" fontSize="14">同一只船 · 船自重不变 · 同一水环境</text>
    </svg>
   </div><div className="boat-status" data-evidence="same-waterline" role="status">{state.waterlineMarked?(m.sameWaterline?'红色标记回到水面了。':m.load<model.elephantMass!?'红色标记在水面上方：船还载得太轻。':'红色标记在水面下方：船载得太重。'):'先把模型象放上船，标下水面碰到船身的位置。'}</div><div className="boat-tools"><button disabled={!state.elephant} onClick={()=>act('remove-elephant',{elephant:false,checked:false})}>把模型象请下船</button><button onClick={mark}>标记模型象的水线</button><button aria-pressed={!!state.passenger} onClick={()=>act('toggle-passenger',{passenger:!state.passenger,checked:false})}>{state.passenger?'请乘员下船':'试试多上一名乘员'}</button></div>{state.error&&<p className="operation-error">{state.error}</p>}
   <div className="object-tray"><Token label="模型象上船" code="elephant" onClick={board} disabled={!!state.elephant}><svg width="70" height="60" viewBox="-85 -115 170 120" aria-hidden="true"><Elephant/></svg></Token>{stones.map(s=><Token key={s.id} label={`${s.name}上船`} code={`stone:${s.id}`} disabled={ids.includes(s.id)} onClick={()=>add(s.id)}><span className="stone-icon">{s.id+1}</span></Token>)}</div><p className="hands-notice">可以拖进船舱，也可以点击物件。装错了？点击下面的石块把它拿走。</p><div className="onboard-stones">{ids.map(id=><button key={id} onClick={()=>act('remove-stone',{boatStones:ids.filter(i=>i!==id),checked:false})}>取走石块{id+1}</button>)}</div></div>
   <aside className="hands-tools stone-scale" data-evidence="stone-scale"><h4>分批称船上的石块</h4><p>小秤一次只称一块。先选择，再称量，把每次读数记下来。</p><select aria-label="要称的石块" value={selected??''} onChange={e=>act('select-stone',{weighingStone:Number(e.target.value)})}><option value="" disabled>选择船上的石块</option>{ids.map(id=><option key={id} value={id}>石块{id+1}</option>)}</select><div className="digital-scale"><span>本次称量</span><strong>{selected!==undefined&&weighed.includes(selected)?stones[selected].mass:'—'} <small>g</small></strong></div><button disabled={selected===undefined||!ids.includes(selected)||!!state.elephant} onClick={()=>act('weigh-stone',{weighed:[...new Set([...weighed,selected!])]})}>称这一块，记下读数</button><ul className="weight-records">{known.map(id=><li key={id}><span>石块{id+1}</span><b>{stones[id].mass}克</b></li>)}</ul>{known.length>0&&<p>已经称过的石块合计 {stoneSum} 克。</p>}
    <button disabled={!state.waterlineMarked||!!state.elephant||!allWeighed} onClick={()=>act('check-replacement',{checked:true},m.replacementValid)}>用水线与读数验证替换</button>{state.checked&&<div className="discovery-message">{m.replacementValid?<><b>原载重＝替代石块的总质量</b><p>{ids.map(id=>stones[id].mass).join('＋')}＝{stoneSum}克。模型象也是{stoneSum}克。</p><p>船＋模型象＝船＋石块；两边都有同一只船，可以比较剩下的载重。</p></>:<p>{state.passenger?'乘员也是载重。同水线只能说明“石块＋乘员”和模型象一样重，不能只报石块质量。':'水线还没有相同，石块总质量暂时不能替代模型象。继续添取石块。'}</p>}</div>}
   </aside></div><p className="hands-notice">图中用固定船体、静水、稳定浮起的理想模型表示“载重越大，吃水越深”。水线比较是教学模型，不是实际船舶测量公式。</p>{toolbar}</section>;
 }
 const mode=state.mode??'scale',objects=mode==='container'?containerObjects:scaleObjects,ids=state.scaleItems??[],unit=state.massUnit??'g',mass=scaleMass(ids,mode),weights=state.weights??[],balance=balanceState(weights);
 const add=(id:number)=>{if(!objects[id]||ids.includes(id))return;act('place-on-scale',{scaleItems:mode==='container'?(id===2?[2]:[...ids.filter(i=>i!==2),id]):[...ids,id]})};
 const setMode=(next:string)=>act('change-scale-mode',{mode:next,scaleItems:[],weights:[],checked:false});
 const beamY=151,angle=angleFrame,radians=angle*Math.PI/180,x1=260-145*Math.cos(radians),x2=260+145*Math.cos(radians),y1=beamY-145*Math.sin(radians),y2=beamY+145*Math.sin(radians);
 return <section className="hands-on-workbench mass-workbench" data-model="weigh"><header className="hands-heading"><span className="lab-badge">质量实验台</span><h3>把物体放上秤，让读数说话</h3><p>先选实验：换单位、分开称杯和水，或用砝码让两边平衡。</p></header><div className="mass-tabs" role="group" aria-label="选择称重实验">{[['scale','电子秤与单位'],['container','杯、水与净重'],['balance','天平与砝码']].map(([id,name])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}>{name}</button>)}</div>
  {mode==='balance'?<div className="balance-layout"><div className="balance-stage" data-evidence="balance" onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=dropId(e,'weight');if(id!==null&&id<balanceWeights.length&&weights.length<12)act('place-weight',{weights:[...weights,id]})}} aria-label="天平右盘，拖入砝码"><svg viewBox="0 0 520 350" role="img" aria-label={`左盘${balance.leftMass}克，右盘${balance.rightMass}克，${balance.balanced?'平衡':balance.difference>0?'左盘较重下沉':'右盘较重下沉'}`}>
   <path d="M225 304H295L278 289H242Z" fill="#527eab"/><path d="M260 155V290" stroke="#527eab" strokeWidth="13"/><circle cx="260" cy="151" r="12" fill="#e9b44d"/><line data-beam-angle={angleFrame} x1={x1} y1={y1} x2={x2} y2={y2} stroke="#735938" strokeWidth="10" strokeLinecap="round"/>
   {[{x:x1,y:y1,left:true},{x:x2,y:y2,left:false}].map(p=><g key={String(p.left)}><path d={`M${p.x} ${p.y}L${p.x-56} ${p.y+86}M${p.x} ${p.y}L${p.x+56} ${p.y+86}`} fill="none" stroke="#735938" strokeWidth="2"/><path d={`M${p.x-58} ${p.y+86}Q${p.x} ${p.y+125} ${p.x+58} ${p.y+86}Z`} fill="#e9b44d" stroke="#735938" strokeWidth="2"/>{p.left?<g transform={`translate(${p.x-25} ${p.y+22})`}><rect width="50" height="60" rx="4" fill="#527eab"/><text x="25" y="36" textAnchor="middle" fill="#fff" fontSize="14">{balance.leftMass}g</text></g>:weights.map((id,i)=><g key={i} transform={`translate(${p.x-39+(i%3)*27} ${p.y+62-Math.floor(i/3)*20})`}><path d="M0 18L3 0H18L21 18Z" fill="#708b89"/><text x="10" y="12" textAnchor="middle" fill="#fff" fontSize="9">{balanceWeights[id]}</text></g>)}<text x={p.x} y={p.y+135} textAnchor="middle" fontSize="15" fill="#253f43">{p.left?balance.leftMass:balance.rightMass}克</text></g>)}
  </svg><p className="boat-status" role="status">{balance.balanced?'两边一样重，横梁水平。':balance.difference>0?'左盘较重，左盘低、右盘高。':'右盘较重，右盘低、左盘高。'}</p></div><aside className="hands-tools"><h4>把砝码拖到右盘</h4><div className="object-tray">{balanceWeights.map((w,id)=><Token label={`添加${w}克砝码`} code={`weight:${id}`} key={id} disabled={weights.length>=12} onClick={()=>act('place-weight',{weights:[...weights,id]})}><span className="weight-icon">{w}g</span></Token>)}</div><p>可以添加过多的砝码，看看哪边会下降。</p><div className="onboard-stones">{weights.map((id,i)=><button key={i} onClick={()=>act('remove-weight',{weights:weights.filter((_,j)=>j!==i)})}>取走{balanceWeights[id]}克</button>)}</div><p className="math-strip">{balance.leftMass} {balance.difference===0?'＝':balance.difference>0?'＞':'＜'} {weights.length?weights.map(id=>balanceWeights[id]).join('＋'):'0'}（克）</p></aside></div>:<div className="scale-layout"><div><div className="scale-platform" data-evidence="scale" onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=dropId(e,'scale');if(id!==null)add(id)}} aria-label="电子秤秤盘，拖入物体"><div className="scale-pan">{ids.length?ids.map(id=><button key={id} className="lab-object-arrival" aria-label={`从秤上拿走${objects[id].name}`} onClick={()=>act('remove-from-scale',{scaleItems:ids.filter(i=>i!==id)})}><ItemIcon id={id} container={mode==='container'}/><span>{objects[id].name}</span></button>):<p>把物品拖到这里<br/>也可点击下面的物品</p>}</div><div className="digital-scale"><span>秤已归零 · 量程5千克</span><strong>{unit==='g'?mass:mass/1000}<small>{unit}</small></strong></div><div className="unit-toggle" data-evidence="unit"><button aria-pressed={unit==='g'} onClick={()=>act('change-mass-unit',{massUnit:'g'})}>用克显示</button><button aria-pressed={unit==='kg'} onClick={()=>act('change-mass-unit',{massUnit:'kg'})}>用千克显示</button></div></div><div className="object-tray">{objects.map(o=><Token key={o.id} label={`称${o.name}`} code={`scale:${o.id}`} disabled={ids.includes(o.id)} onClick={()=>add(o.id)}><ItemIcon id={o.id} container={mode==='container'}/></Token>)}</div></div><aside className="hands-tools"><h4>{mode==='container'?'同一杯水，拆开分别称':'单位变了，物体没变'}</h4>{mode==='container'?<div data-evidence="container"><p>空杯120克，水260克，装水的杯子380克。先拿走上一次的物品，再分别称。</p><p>把“杯和水”与“空杯＋单独的水”分别放上秤，比较读数。</p><button onClick={()=>act('place-on-scale',{scaleItems:[2]})}>称完整的一杯水</button><button onClick={()=>act('place-on-scale',{scaleItems:[0,1]})}>拆开称：空杯＋水</button><p className="math-strip">杯＋水＝总质量<br/>120＋260＝380<br/>水＝380－120＝260克</p></div>:<><p>同一袋米：1000克＝1千克。换显示单位不会改变米袋的质量。</p><p className="math-strip">当前物品 {mass}克＝{mass/1000}千克</p><p>电子秤记录质量；天平比较两边的质量。</p></>}</aside></div>}{toolbar}</section>;
}
