import type {OperationModel} from '../../../shared/operation-models.mjs';
import {measureOperationModel} from '../../../shared/operation-models.mjs';
import {buildReverseAddMultiplyFlow,expressionASTText} from '../../../shared/pilot-math.mjs';
import type {WidgetFields,WidgetState} from '../types';
import OperationVisual,{ArrayVisual} from './OperationVisual';

export default function OperationExtensionLab({model,value,onChange}:{model:OperationModel;value:WidgetState;onChange:(state:WidgetState)=>void}){
  const state=value.extensionVersion===1?value:{},observed=Boolean(state.observed);
  const update=(patch:WidgetFields)=>onChange({...state,...patch,stateKind:'operation-extension',extensionVersion:1,modelType:model.type});
  const snapshot=(s:WidgetFields)=>JSON.stringify({parameter:s.parameter??('cut' in model?model.cut:1),choice:s.choice??null,reverseStep:s.reverseStep??0,transposed:!!s.transposed,observed:!!s.observed});
  const record=(action:string,patch:WidgetFields)=>update({...patch,actions:[...(Array.isArray(state.actions)?state.actions:[]).slice(-29),{action,before:snapshot(state),after:snapshot({...state,...patch}),valid:action!=='reverse-attempt'&&(action!=='execute-wallet'||state.choice==='subtract')&&(action!=='share-cards'||state.choice==='multiply'),at:new Date().toISOString()}]});
  const reset=()=>onChange({stateKind:'operation-extension',extensionVersion:1,modelType:model.type});
  const prediction=<div><button className="studio-ghost" aria-pressed={!!state.predicted} onClick={()=>update({predicted:true})}>我已想过，动手核对</button><label className="lab-prediction">操作前，我预测<input value={state.prediction??''} maxLength={120} placeholder="可不写，也可以先口头说出想法" onChange={e=>update({prediction:e.target.value,observed:false})}/></label></div>;
  const compare=<button className="studio-primary" disabled={false} onClick={()=>record('compare-prediction',{observed:true})}>执行并核对预测</button>;
  const footer=<><label className="lab-prediction">我用哪条关系解释？<textarea maxLength={200} value={state.explanation??''} onChange={e=>update({explanation:e.target.value})}/></label><p className="muted">参数、预测、操作和解释都会随课程保存。完成操作表示探索过，独立迁移与隔日复习另行记录。</p><button className="studio-ghost" onClick={reset}>重新探索</button></>;
  if(model.type==='split-array'||model.type==='laws'){
    const transposed=model.type==='laws'&&Boolean(state.transposed),cols=model.cols,rows=model.rows,cut=Math.max(1,Math.min(cols-1,Number(state.parameter)||('cut' in model?model.cut:1))),m=measureOperationModel(model,{cut});
    return <div className="operation-extension-lab"><h3>{model.type==='laws'?'换方向数同一块点阵':'拖动切割线，把整块拆成两块'}</h3><p>{rows}行，每行{cols}个点。改变分块方式后，总数会怎样？</p>{prediction}<ArrayVisual rows={rows} cols={cols} cut={cut} transposed={transposed} onCut={n=>record('move-cut',{parameter:n,observed:false})}/><label className="cut-control">切割线：{transposed?`上方${cut}行，下方${cols-cut}行`:`左边${cut}列，右边${cols-cut}列`}<input type="range" min="1" max={cols-1} value={cut} onChange={e=>record('move-cut',{parameter:Number(e.target.value),observed:false})}/></label>{model.type==='laws'&&<button className="studio-ghost" onClick={()=>record('swap-count-direction',{transposed:!state.transposed,observed:false})}>换计数方向：{state.transposed?`${cols}组，每组${rows}`:`${rows}组，每组${cols}`}</button>}{compare}{observed&&<div className="model-result" role="status"><b>{rows}×{cut}＋{rows}×{cols-cut}＝{m.left}＋{m.right}＝{m.total}</b><p>{transposed?'每一列的上下两块':'每一行的左右两块'}都要计算。若只加一次第二块的{cols-cut}个，就漏掉其余{rows-1}份的{m.missed}个。</p>{model.type==='laws'&&<p>{rows}×{cols}＝{cols}×{rows}，同一批点没有增加或减少。三堆珠子也一样：({model.piles[0]}＋{model.piles[1]})＋{model.piles[2]}＝{model.piles[0]}＋({model.piles[1]}＋{model.piles[2]})＝{model.piles.reduce((a,b)=>a+b,0)}。</p>}</div>}{footer}</div>;
  }
  if(model.type==='reverse'){
    const flow=buildReverseAddMultiplyFlow(model.addend,model.multiplier,model.target),step=Math.min(2,Math.max(0,Number(state.reverseStep)||0));
    return <div className="operation-extension-lab"><h3>先查错算者走过的路线</h3><p>题目是{model.addend}＋□×{model.multiplier}。有人先把{model.addend}和□加起来，再乘{model.multiplier}，得到{model.target}。□是多少？</p><OperationVisual model={model} observed={observed} step={step}/><div className="flow-equation">□ → ＋{model.addend} → ×{model.multiplier} → {model.target}</div>{prediction}<div className="prediction-panel"><b>从结果往回走，下一步撤销哪一个动作？</b>{(step===0?[['divide',`除以${model.multiplier}`],['subtract',`减去${model.addend}`]]:[['subtract',`减去${model.addend}`],['multiply',`乘${model.multiplier}`]]).map(([id,label])=><button key={id} disabled={step===2} onClick={()=>id===(step===0?'divide':'subtract')?record('reverse-'+id,{reverseStep:step+1,error:'',observed:step===1}):record('reverse-attempt',{error:`先撤销最后发生的动作。加${model.addend}后乘${model.multiplier}，所以倒着先除${model.multiplier}，再减${model.addend}。`})}>{label}</button>)}</div>{state.error&&<p className="operation-error">{state.error}</p>}{step>0&&<p className="flow-equation">{flow.inverseSteps.slice(0,step).join(' → ')}</p>}{step===2&&<div className="model-result"><b>找回□＝{flow.unknown}，分别验证两条路线</b><p>错算者实际执行：{flow.forwardText}</p><p>题目本来要求：{expressionASTText(flow.intended)}＝{flow.intendedValue}</p><p>{model.target}证明我们找回了错算者的输入；{flow.intendedValue}才是题目原式的结果。</p></div>}{footer}</div>;
  }
  const m=measureOperationModel(model);
  if(model.type==='wallet')return <div className="operation-extension-lab"><h3>把付款、退款合成一次净支出</h3><p>有{model.start}元，付出{model.pay}元，后来退回{model.refund}元。选一张净支出卡，让两条路线表示同一笔钱。</p>{prediction}<OperationVisual model={model} observed={observed} choice={state.choice}/><div className="flow-equation">{model.start} → 付{model.pay} → 退{model.refund}</div><div className="prediction-panel">{['subtract','add'].map(id=><button aria-pressed={state.choice===id} key={id} onClick={()=>record('choose-net-payment',{choice:id,observed:false})}>{model.pay}{id==='subtract'?'－':'＋'}{model.refund}</button>)}</div><button className="studio-primary" disabled={!state.choice} onClick={()=>record('execute-wallet',{observed:true})}>把净支出放进钱袋</button>{observed&&<div className="model-result"><b>逐笔余额：{m.final}元 · 一次扣款余额：{state.choice==='subtract'?m.final:m.counterexample}元</b><p>{state.choice==='subtract'?`退款减少支出：${model.start}－(${model.pay}－${model.refund})＝${model.start}－${model.pay}＋${model.refund}。`:'把退款又扣一次，会少掉两份退款。撤回，改选另一张卡核对。'}</p></div>}{footer}</div>;
  if(model.type==='division-groups')return <div className="operation-extension-lab"><h3>人数要用“组数×每组人数”连接</h3><p>{model.total}张卡片，分给{model.groups}组，每组{model.perGroup}人，每人同样多。</p>{prediction}<OperationVisual model={model} observed={observed} choice={state.choice}/><div className="prediction-panel">{['multiply','divide'].map(id=><button key={id} aria-pressed={state.choice===id} onClick={()=>record('choose-total-people',{choice:id,observed:false})}>总人数＝{model.groups}{id==='multiply'?'×':'÷'}{model.perGroup}</button>)}</div><button className="studio-primary" disabled={!state.choice} onClick={()=>record('share-cards',{observed:true})}>按选择平均分</button>{observed&&<div className="model-result"><b>{state.choice==='multiply'?`图中${m.people}人，每人${m.perPerson}张。`:`图中实际有${m.people}人；${model.groups}÷${model.perGroup}不能表示图中的总人数。`}</b><p>{model.total}÷{model.groups}÷{model.perGroup}＝{model.total}÷({model.groups}×{model.perGroup})＝{m.perPerson}。</p></div>}{footer}</div>;
  return <div className="operation-extension-lab"><h3>方框必须包住完整的一盒</h3><p>每盒{model.left}个红物件和{model.right}个蓝物件，共{model.copies}盒。你要把“每盒总数”换个名字。</p>{prediction}<OperationVisual model={model} observed={observed} choice={state.choice}/><div className="prediction-panel"><button aria-pressed={state.choice==='whole'} onClick={()=>record('select-whole',{choice:'whole',observed:false})}>□包住（{model.left}＋{model.right}）</button><button aria-pressed={state.choice==='partial'} onClick={()=>record('select-part',{choice:'partial',observed:false})}>□只包住{model.right}</button></div><button className="studio-primary" disabled={!state.choice} onClick={()=>record('substitute',{observed:true})}>替换所选对象</button>{observed&&<div className="model-result"><b>{state.choice==='whole'?`□＝${m.whole}，□×${model.copies}＝${m.total}`:`□＝${model.right}，每盒总数仍是${model.left}＋□，总数是（${model.left}＋□）×${model.copies}`}</b><p>名字只记一个确定的量。换掉一部分时，其他部分必须留下；两种合法替换都应得到{m.total}。</p></div>}{footer}</div>;
}
