import {boxFaces,cubeProjection,faceRelation,faces,foldedFaces,hiddenCubes,type HandsOnModel} from '../../../shared/hands-on-models.mjs';
import type {WidgetState} from '../types';
import SolidView from './SolidView';
import {useHandsOn} from './useHandsOn';
import './hands-on.css';

const views=[{id:'front',label:'正前方',azimuth:0,elevation:0},{id:'right',label:'右侧',azimuth:90,elevation:0},{id:'top',label:'上方',azimuth:0,elevation:90}] as const;
function Projection({view,rear,dimensions}:{view:typeof views[number];rear?:number;dimensions?:number[]}){
 const cells=rear===undefined?null:cubeProjection(rear,view.id),[w,h,d]=dimensions??[1,1,1],width=view.id==='right'?d:w,height=view.id==='top'?d:h,face=faces.find(f=>f.id===(view.id==='front'?3:view.id==='right'?4:1))!;
 return <figure className="projection-card" data-evidence="projection" data-view={view.id}><figcaption>{view.label}拍到的照片</figcaption><svg viewBox="0 0 150 115" role="img" aria-label={cells?`${view.label}投影：${cells.length}个方格`:`${view.label}投影：${face.name}`}>
  {cells?cells.map(cell=>{const [x,y]=cell.split(',').map(Number);return <rect key={cell} x={50+x*25} y={75-y*25} width="25" height="25" fill="#e9b44d" stroke="#735938" strokeWidth="1.5"/>}):<><rect x={75-width*20} y={56-height*20} width={width*40} height={height*40} rx="2" fill={['#f8edca','#e7ddef','#f5ded7','#dee8f2','#d6ebe2','#ebdecc'][face.id-1]}/><text x="75" y="64" textAnchor="middle" fill={face.color} fontSize="24">{face.mark}</text></>}
 </svg></figure>;
}

export default function SpatialWorkbench({model,sceneId,value,onChange}:{model:HandsOnModel;sceneId:string;value:WidgetState;onChange:(s:WidgetState)=>void}){
 const {state,act,toolbar}=useHandsOn(model,sceneId,value,onChange),azimuth=state.cameraAzimuth??25,elevation=state.cameraElevation??20,rear=state.rearHeight??1,fold=state.foldProgress??0;
 const rotate=(a:number,e:number)=>act('rotate-camera',{cameraAzimuth:a,cameraElevation:e});
 const currentView=views.find(v=>Math.abs(v.azimuth-azimuth)<1&&Math.abs(v.elevation-elevation)<1);
 const setView=(view:typeof views[number])=>act('change-view',{cameraAzimuth:view.azimuth,cameraElevation:view.elevation});
 const solid=model.mode==='fold'?foldedFaces(fold):model.mode==='hidden'?hiddenCubes(rear).flatMap(({x,y,z})=>boxFaces(1,1,1,[x,-y,z-.5])):boxFaces(...(model.dimensions as [number,number,number]));
 const selected=state.faceId??1,other=state.otherFaceId??5,relation=faceRelation(selected,other),photos=state.photos??[];
 const focusFace=(id:number)=>{const camera:{[id:number]:[number,number]}={1:[25,55],2:[310,20],3:[25,20],4:[65,20],5:[25,-35],6:[155,20]};act('select-face',{faceId:id,otherFaceId:id===other?({1:5,2:4,3:6,4:2,5:1,6:3} as Record<number,number>)[id]:other,checked:false,cameraAzimuth:camera[id][0],cameraElevation:camera[id][1]})};
 return <section className="hands-on-workbench spatial-workbench" data-model={model.mode}>
  <header className="hands-heading"><span className="lab-badge">空间实验台</span><h3>{model.mode==='observe'?'盒子不动，让相机去旅行':model.mode==='hidden'?'正面一样，背后可能不一样':'六张面，一起折成一个盒子'}</h3><p>{model.mode==='observe'?'红面朝前、蓝面朝右、星星在上面。拖动相机视角，再正对三个方向拍照。':model.mode==='hidden'?'前排固定有2块。你可以在后排加积木，再看正面照片是否变了。': '拖动折叠滑条，跟踪每个编号的面。纸没有剪掉，面也没有换名字。'}</p></header>
  <div className="spatial-layout"><div className="hands-stage"><SolidView solid={solid} azimuth={azimuth} elevation={elevation} title={model.mode==='fold'?`六面展开图，折叠${fold}%`:model.mode==='hidden'?`前排2块，后排${rear}块积木`:'固定的红蓝黄三面盒子'} marked={model.mode==='observe'} selected={model.mode==='fold'?selected:undefined} onFace={model.mode==='fold'?focusFace:undefined} onRotate={rotate}/>
   <div className="observer-strip" data-evidence="observer"><span aria-hidden="true">◉</span><b>观察者：相机</b><span data-evidence="direction">{currentView?`正对${currentView.label}`:`绕盒子${Math.round(azimuth)}°，抬高${Math.round(elevation)}°`}</span><small>物体固定在桌上</small></div>
   <div className="view-controls">{views.map(v=><button key={v.id} aria-pressed={currentView?.id===v.id} onClick={()=>setView(v)}>从{v.label}看</button>)}</div>
  </div><aside className="hands-tools">
   {model.mode==='observe'&&<><h4>留一张照片</h4><p>先选正前方、右侧或上方，再按拍照。比较的是同一个盒子。</p><button disabled={!currentView||photos.length>=6} onClick={()=>act('take-photo',{photos:[...photos,views.findIndex(v=>v.id===currentView!.id)]})}>拍下当前方向</button>{photos.length>0&&<div className="photo-shelf" aria-label="保存的照片">{photos.map((v,i)=><Projection key={i} view={views[v]} dimensions={model.dimensions}/>)}</div>}</>}
   {model.mode==='hidden'&&<><h4>改变被遮住的后排</h4><div className="rear-tools" data-evidence="hidden-cubes"><button disabled={rear===0} onClick={()=>act('remove-cube',{rearHeight:rear-1})}>拿走后排1块</button><strong>后排 {rear} 块</strong><button disabled={rear===2} onClick={()=>act('add-cube',{rearHeight:rear+1})}>后排加1块</button></div><p>先记住正面照片，再加一块。哪张照片能帮你分辨？</p><div className="prediction-chips">{['正面','右面','上面'].map(text=><button key={text} aria-pressed={state.prediction===text} onClick={()=>act('predict-view',{prediction:text,checked:false})}>我选{text}</button>)}</div><button disabled={!state.prediction} onClick={()=>act('compare-view',{checked:true},state.prediction==='右面')}>用照片核对我的选择</button>{state.checked&&<p className="discovery-message">{state.prediction==='右面'?'右面能看到前后两排各有多高。':'对比后排1块与2块：正面都是2格，上面都是2格；右面才能分辨后排高度。'}</p>}<p className="math-strip">实际总数：2＋{rear}＝{2+rear}块。正面仍只看见2格。</p></>}
   {model.mode==='fold'&&<><h4>把同一张纸折回去</h4><label className="fold-control" data-evidence="fold-progress">折叠程度 {Math.round(fold)}%<input aria-label="折叠程度" type="range" min="0" max="100" value={fold} onChange={e=>act('fold-paper',{foldProgress:Number(e.target.value)})}/></label><div className="view-controls"><button onClick={()=>act('fold-paper',{foldProgress:0})}>完全展开</button><button onClick={()=>act('fold-paper',{foldProgress:50})}>折到一半</button><button onClick={()=>act('fold-paper',{foldProgress:100})}>折成盒子</button></div><div className="face-picker" data-evidence="face-identity">{faces.map(f=><button key={f.id} aria-pressed={selected===f.id} onClick={()=>focusFace(f.id)} style={{borderColor:f.color}}>{f.id}号 · {f.name}</button>)}</div><p data-evidence="hinge">1、2、4、5沿3号面的边转动；6沿5号面的外边转动。</p><label>和几号面比较？<select aria-label="比较的面" value={other} onChange={e=>act('select-other-face',{otherFaceId:Number(e.target.value),checked:false})}>{faces.filter(f=>f.id!==selected).map(f=><option key={f.id} value={f.id}>{f.id}号 · {f.name}</option>)}</select></label><div className="prediction-chips">{['相邻','相对'].map(text=><button key={text} aria-pressed={state.prediction===text} onClick={()=>act('predict-relation',{prediction:text,checked:false})}>我认为{text}</button>)}</div><button disabled={fold!==100||!state.prediction||selected===other} onClick={()=>act('check-faces',{checked:true},state.prediction===(relation==='opposite'?'相对':'相邻'))}>折好后核对两面</button>{state.checked&&<p className="discovery-message" data-evidence="opposite-faces">{selected}号和{other}号{relation==='opposite'?'相对，不共用棱':'相邻，共用一条棱'}。{state.prediction===(relation==='opposite'?'相对':'相邻')?'你的判断吻合。':'再转动视角，看看它们是否接在同一条边上。'}</p>}</>}
  </aside></div>
  {model.mode!=='fold'&&<div className="projection-row" aria-label="三个方向的正投影">{views.map(view=><Projection key={view.id} view={view} rear={model.mode==='hidden'?rear:undefined} dimensions={model.dimensions}/>)}</div>}
  <p className="hands-notice">{model.mode==='fold'?'展开图在平面上不挨着的面，折起来也可能相邻。先选两面作判断，再折好、转动视角核对。':'主画面表示立体物体；下面三张照片是正对各面的投影。看见的部分和物体全部，是两回事。'}</p>{model.mode==='fold'&&<p className="hands-notice"><a href="/math-paper-folding/print-templates.html" target="_blank" rel="noopener noreferrer">打开已有的等比例折纸模板，打印后亲手试</a><br/>纸模板是其他展开方式，编号与这里不同。先标记六个面，再检查是否重叠、有缺口。</p>}{toolbar}
 </section>;
}
