import type {TextbookModel} from '../../../shared/textbook-models.mjs';
import type {WidgetState} from '../types';
import {useTextbook} from './useTextbook';
import {Board,DragPoint,clamp,Heading,Feedback,colors} from './Primitives';
export default function AngleWorkbench(props:{model:TextbookModel;sceneId:string;value:WidgetState;onChange:(s:WidgetState)=>void}){
 const {state:s,act,toolbar,measured:m}=useTextbook(props.model,props.sceneId,props.value,props.onChange),a=s.angle!,r=s.rotation!,len=s.sideLength!,rad=(d:number)=>d*Math.PI/180,point=(d:number,l=len)=>({x:270+l*Math.cos(rad(d)),y:220-l*Math.sin(rad(d))}),p=point(r),q=point(r+a),ref=point(props.model.angle!,125),upper=(x:number,y:number)=>{const absolute=Math.atan2(220-y,x-270)*180/Math.PI;act('rotate-ray',{angle:clamp((absolute-r+360)%360,1,179)})};
 return <section className="textbook-workbench" data-textbook-model="angle"><Heading model={props.model}>金色端点拖动上边的方向；下边端点拖动边长。整角旋转时，两条边一起转。淡虚线保留原来的角。</Heading><Board title="可以拖动的两条射线和直角叠合工具" height={420}>
 <path d={`M395 220H270L${ref.x} ${ref.y}`} transform={`rotate(${-r} 270 220)`} fill="none" stroke={colors.blue} strokeOpacity=".24" strokeWidth="5" strokeDasharray="8 6"/>
 {s.show&&<g transform={`rotate(${-r} 270 220)`}><path d="M270 220H375V115H270Z" fill={colors.gold} fillOpacity=".15" stroke={colors.gold} strokeWidth="2"/><path d="M294 220V196H270" fill="none" stroke={colors.ink} strokeWidth="2"/></g>}
 <path d={`M${p.x} ${p.y}L270 220L${q.x} ${q.y}`} fill="none" stroke={colors.blue} strokeWidth="8" strokeLinecap="round"/><circle cx="270" cy="220" r="6" fill={colors.ink}/><DragPoint x={q.x} y={q.y} label="转动上边改变张口" onMove={upper}/><DragPoint x={p.x} y={p.y} label="拉长下边不改变方向" onMove={(x,y)=>act('lengthen-ray',{sideLength:clamp(Math.hypot(x-270,y-220),55,170)})}/><text x="270" y="400" textAnchor="middle" fill={colors.ink}>只改变边长，张口不变；只转动一条边，张口改变。</text></Board>
 <div className="textbook-controls"><label>张口<input type="range" aria-label="角的张口" min="1" max="179" value={a} onChange={e=>act('rotate-ray',{angle:Number(e.target.value)})}/></label><label>边的画出长度<input type="range" aria-label="角的边长" min="55" max="170" value={len} onChange={e=>act('lengthen-ray',{sideLength:Number(e.target.value)})}/></label><label>整个角一起转<input type="range" aria-label="整角旋转" min="0" max="359" value={r} onChange={e=>act('rotate-whole',{rotation:Number(e.target.value)})}/></label><button onClick={()=>act('overlay-right-angle',{show:!s.show})}>{s.show?'收起直角工具':'叠上直角工具'}</button><button onClick={()=>act('rotate-ray',{angle:90})}>让上边对齐直角边</button></div><Feedback error={s.error}>张口记录为{m.degrees}°，是{m.kind}。边画得长或短，都没有改变这个张口。</Feedback>{toolbar}</section>;
}
