import type {TextbookModel} from '../../../shared/textbook-models.mjs';
import type {WidgetState} from '../types';
import {useTextbook} from './useTextbook';
import {Token,dropCode,Heading,Feedback,colors} from './Primitives';
function Material({place}:{place:number}){const rows=place===2?1:10,cols=place===0?10:1,w=cols*7,h=rows*7;return <svg className="base-ten-material" viewBox={`0 0 ${w} ${h}`} style={{width:w,height:h}} aria-hidden="true">{Array.from({length:rows*cols},(_,n)=><rect key={n} x={n%cols*7} y={Math.floor(n/cols)*7} width="6" height="6" rx="1" fill={[colors.gold,colors.green,colors.blue][place]}/>)}</svg>}
export default function BankWorkbench({model,sceneId,value,onChange}:{model:TextbookModel;sceneId:string;value:WidgetState;onChange:(s:WidgetState)=>void}){
 const {state:s,act,toolbar,measured:m}=useTextbook(model,sceneId,value,onChange),bank=s.bank!,alloc=s.alloc!,names=['百','十','一'];
 const exchange=(i:number,up:boolean)=>{const next=[...bank];if(up){if(i===0||bank[i]<10){act('exchange',{error:'先凑够10个同样的计数单位，再换成高一位的1个。'},false);return}next[i]-=10;next[i-1]++}else{if(i===2||bank[i]<1)return;next[i]--;next[i+1]+=10}act('exchange',{bank:next})};
 const give=(group:number,unit:number)=>{if(!Number.isInteger(unit)||unit<0||unit>2||bank[unit]===0){act('allocate',{error:'这个计数单位已经分完了。可以先拆开一捆。'},false);return}const b=[...bank],a=[...alloc];b[unit]--;a[group*3+unit]++;act('allocate',{bank:b,alloc:a})};
 const takeBack=(group:number,unit:number)=>{if(!alloc[group*3+unit])return;const b=[...bank],a=[...alloc];b[unit]++;a[group*3+unit]--;act('return-material',{bank:b,alloc:a})};
 return <section className="textbook-workbench bank-workbench" data-textbook-model={model.type}><Heading model={model}>{model.type==='division'?'把一捆拖进某个人的框。剩下的一捆可以拆成10个低一位单位；也可以点击分配按钮；分错了，可以退回材料再分。':'开始时有3个十、18个一。把10个一换成1个十，观察总根数有没有改变。'}</Heading>
 <p className="bank-legend">蓝色小块代表1；绿色一条由10个小块组成；金色一板由10条组成，表示100。</p><div className="bank-places">{bank.map((count,i)=><article key={i}><h4>{names[i]}位 · 待整理{count}个{names[i]}</h4><div className="bank-material" role="img" aria-label={`${count}个${names[i]}，表示${count*[100,10,1][i]}个一`}>{Array.from({length:count},(_,n)=><i key={n} className={'bank-unit unit-'+i}><Material place={i}/></i>)}</div><div className="textbook-controls">{i<2&&<button disabled={!count} onClick={()=>exchange(i,false)}>拆1个{names[i]} → 10个{names[i+1]}</button>}{i>0&&<button onClick={()=>exchange(i,true)}>捆10个{names[i]} → 1个{names[i-1]}</button>}{model.groups&&<Token disabled={!count} code={`bank:${i}`} label={`拿1个${names[i]}去分配`}/>}</div></article>)}</div>
 {model.groups&&<div className="bank-recipients">{Array.from({length:model.groups},(_,g)=><article className="textbook-dropzone" key={g} onDragOver={e=>e.preventDefault()} onDrop={e=>{const code=dropCode(e);if(/^bank:[0-2]$/.test(code))give(g,Number(code.at(-1)))}}><h4>第{g+1}{model.total===408?'班':'人'}</h4><div className="bank-material recipient-material" role="img" aria-label={`得到${m.shares[g]}个一`}>{alloc.slice(g*3,g*3+3).flatMap((count,i)=>Array.from({length:count},(_,n)=><i key={`${i}-${n}`} className={'bank-unit unit-'+i}><Material place={i}/></i>))}</div><b>{m.shares[g]}{model.total===408?'本':'颗'}</b><div>{names.map((name,i)=><span key={name}><button disabled={!bank[i]} onClick={()=>give(g,i)}>分1个{name}</button><button disabled={!alloc[g*3+i]} onClick={()=>takeBack(g,i)}>退回1个{name}</button></span>)}</div></article>)}</div>}
 <Feedback error={s.error}>{model.groups?(m.equal?`全部分完，${model.groups}份都是${m.shares[0]}；用${m.shares[0]}×${model.groups}回到${model.total}。`:`待分${m.pending}，已分${model.total!-m.pending}，合计始终是${model.total}。分完后还要检查每份一样多。`):(m.normalized?`数位整理好了：${bank[0]}个百、${bank[1]}个十、${bank[2]}个一，仍是${m.total}。`:`数量还是${m.total}；个位现在有${bank[2]}个一，还能再捆成十吗？`)}</Feedback>{toolbar}</section>;
}
