import {gridCells,type TextbookModel} from '../../../shared/textbook-models.mjs';
import type {WidgetState} from '../types';
import {useTextbook} from './useTextbook';
import {Board,DragPoint,Token,dropCode,clamp,Heading,Feedback,colors} from './Primitives';
export default function GeometryWorkbench(props:{model:TextbookModel;sceneId:string;value:WidgetState;onChange:(s:WidgetState)=>void}){
 const {model}=props,{state:s,act,toolbar,measured:m}=useTextbook(model,props.sceneId,props.value,props.onChange),mark=(i:number)=>act('trace-edge',{marked:s.marked!.includes(i)?s.marked!: [...s.marked!,i]});
 if(model.type==='boundary'||model.type==='joining'){
  const joining=model.type==='joining',x=joining?105:145,y=90,w=joining?120:350,h=joining?120:175,x2=x+w+(s.offset??0),joined=joining&&m.joined;
  const sides=joining?(joined?[[x,y,x+w,y],[x+w,y,x+2*w,y],[x+2*w,y,x+2*w,y+h],[x+2*w,y+h,x+w,y+h],[x+w,y+h,x,y+h],[x,y+h,x,y]]:[[x,y,x+w,y],[x+w,y,x+w,y+h],[x+w,y+h,x,y+h],[x,y+h,x,y],[x2,y,x2+w,y],[x2+w,y,x2+w,y+h],[x2+w,y+h,x2,y+h],[x2,y+h,x2,y]]):[[x,y,x+w,y],[x+w,y,x+w,y+h],[x+w,y+h,x,y+h],[x,y+h,x,y]];
  const move=(px:number)=>{let offset=clamp(px-x-w,0,180);if(offset<15)offset=0;act('move-square',{offset,marked:[]})};
  return <section className="textbook-workbench" data-textbook-model={model.type}><Heading model={model}>{joining?'拖第二个方块的金色点，把两块边完整贴合。接缝进入内部后，点击红色外边逐段走；也可用按钮拼好。':'点外边的线段，一次描一条。蓝色已经走过；里面的地面不是要装围栏的位置。'}</Heading><Board title="可拼接和可追踪的外边界" height={355}><rect x={x} y={y} width={w} height={h} fill="#cee2d8"/>{joining&&<rect x={x2} y={y} width={w} height={h} fill="#e2d6b7"/>}{joined&&<line x1={x+w} x2={x+w} y1={y} y2={y+h} stroke={colors.ink} strokeDasharray="6 5" strokeWidth="2"/>}{sides.map(([a,b,c,d],i)=><line role="button" tabIndex={0} aria-label={`描第${i+1}条外边`} key={i} x1={a} y1={b} x2={c} y2={d} stroke={s.marked!.includes(i)?colors.blue:colors.red} strokeWidth="9" onClick={()=>mark(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();mark(i)}}}/>)}{joining?<><text x={x+w/2} y={y-20} textAnchor="middle" fill={colors.ink}>{model.side}厘米</text><text x={x2+w/2} y={y-20} textAnchor="middle" fill={colors.ink}>{model.side}厘米</text><DragPoint x={x2} y={y+h+28} label="拖第二块方形板拼接" step={20} onMove={move}/></>:<><text x={x+w/2} y={y-20} textAnchor="middle" fill={colors.ink}>{model.width}米</text><text x={x-47} y={y+h/2} textAnchor="middle" fill={colors.ink}>{model.height}米</text></>}<text x="320" y="330" textAnchor="middle" fill={colors.ink}>已沿外边走过：{m.walked}{joining?'厘米':'米'}</text></Board><div className="textbook-controls">{joining&&<><button onClick={()=>act('move-square',{offset:0,marked:[]})}>两块完整拼好</button><button onClick={()=>act('move-square',{offset:160,marked:[]})}>把两块分开</button></>}{sides.map((_,i)=><button key={i} aria-pressed={s.marked!.includes(i)} onClick={()=>mark(i)}>描第{i+1}条外边</button>)}</div><Feedback error={s.error}>{s.marked!.length===sides.length?`这一圈全部描完，是${m.perimeter}${joining?'厘米':'米'}。`:'先亲手走完一圈，再合计各段长度。'}{joined?'原来两条贴合的边都留在内部，不再计入外边界。':''}</Feedback>{toolbar}</section>;
 }
 if(model.type==='cut-area'){
  const cells=gridCells(model,s),scale=40,x=80,y=30;
  return <section className="textbook-workbench" data-textbook-model="cut-area"><Heading model={model}>原纸是8列5行，角上3列2行剪下来，但不丢掉。拖动金色点移动这一块；不要盖住原纸。面积数方格，周长数露在外面的单位边。</Heading><Board title="原纸与可移动的3乘2剪块" height={390}>{cells.map(([a,b],i)=><rect key={i} x={x+a*scale} y={y+b*scale} width={scale} height={scale} fill={i<model.cols!*model.rows!-model.cutCols!*model.cutRows!?'#bcd9cb':'#e9c177'} stroke="#fff" strokeWidth="2"/>)}<rect x={x+s.left!*scale} y={y+s.top!*scale} width={model.cutCols!*scale} height={model.cutRows!*scale} fill="none" stroke={colors.gold} strokeWidth="3"/><DragPoint x={x+s.left!*scale} y={y+s.top!*scale} label="移动剪下的方块" step={40} onMove={(a,b)=>act('move-cutout',{left:clamp((a-x)/scale,0,9),top:clamp((b-y)/scale,0,6)})}/><text x="320" y="365" textAnchor="middle" fill={colors.ink}>材料一直保留40个单位方格</text></Board><div className="textbook-controls"><button onClick={()=>act('move-cutout',{left:8,top:0})}>把剪块移到右边</button><button onClick={()=>act('move-cutout',{left:5,top:3})}>拼回原来的缺口</button></div><Feedback error={s.error}>{m.overlap?`有${m.overlap}格重叠，覆盖位置只剩${m.area}格；材料没有变少，但不能用重叠图冒充完整铺满。`:`面积${m.area}个单位格保持不变，现在所有外边共有${m.perimeter}条单位边。`}</Feedback>{toolbar}</section>;
 }
 const cols=model.cols!,rows=model.rows!,scale=48,x=90,y=35,fill=(i:number)=>{if(!s.filled!.includes(i))act('place-tile',{filled:[...s.filled!,i]})};
 return <section className="textbook-workbench" data-textbook-model="tiling"><Heading model={model}>把一块1平方米方砖拖进空格，或点空格铺一块。填满一行后，再看看有几行；已经铺过的格子不会重复计数。</Heading><div className="tiling-layout"><Token code="unit-tile" label="拖一块1平方米方砖"><span className="unit-tile-icon">1 m²</span></Token><Board title="6米乘4米地面的单位格" height={300}>{Array.from({length:cols*rows},(_,i)=><rect key={i} role="button" tabIndex={0} aria-label={`铺第${i+1}块方砖`} x={x+i%cols*scale} y={y+Math.floor(i/cols)*scale} width={scale} height={scale} fill={s.filled!.includes(i)?colors.green:'#f8edd6'} stroke={colors.ink} strokeWidth="1" onDragOver={e=>e.preventDefault()} onDrop={e=>{if(dropCode(e)==='unit-tile')fill(i)}} onClick={()=>fill(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fill(i)}}}/>)}<text x={x+cols*scale/2} y="277" textAnchor="middle" fill={colors.ink}>每行6块，共4行；已铺{m.area}块</text></Board></div><div className="textbook-controls"><button onClick={()=>{const row=m.fullRows.findIndex((n:number)=>n<cols);if(row>=0)act('fill-one-row',{filled:[...new Set([...s.filled!,...Array.from({length:cols},(_,c)=>row*cols+c)])]})}}>按这一行补齐方砖</button><button disabled={!s.filled!.length} onClick={()=>act('take-tile',{filled:s.filled!.slice(0,-1)})}>拿回最后一块</button></div><Feedback error={s.error}>{m.area===m.total?`铺满以后：6×4＝${m.area}，每块1平方米，共${m.area}平方米。`:`铺了${m.area}平方米；各行分别有${m.fullRows.join('、')}块。`}</Feedback>{toolbar}</section>;
}
