import {useMotionValue} from '../useMotionValue';
import {projectPoint} from '../../../shared/hands-on-models.mjs';
import type {TextbookModel} from '../../../shared/textbook-models.mjs';
import type {WidgetState} from '../types';
import {useTextbook} from './useTextbook';
import {Board,DragPoint,clamp,Heading,Feedback,colors} from './Primitives';
export default function MotionWorkbench(props:{model:TextbookModel;sceneId:string;value:WidgetState;onChange:(s:WidgetState)=>void}){
 const {state:s,act,toolbar}=useTextbook(props.model,props.sceneId,props.value,props.onChange),foldFrame=useMotionValue(s.angle??0,650);
 if(props.model.type==='paper-fold'){
  const angle=s.angle!,theta=foldFrame*Math.PI/180,project=(x:number,y:number,right=false)=>{const p=projectPoint([right?x*Math.cos(theta):x,y,right?x*Math.sin(theta):0],22,18);return `${320+p.x*140},${153+p.y*110}`},polygon=(right=false)=>[[right?0:-1,-.7],[right?1:0,-.7],[right?1:0,.7],[right?0:-1,.7]].map(([x,y])=>project(x,y,right)).join(' '),holes=(right:boolean)=>s.marked!.map(n=>{const x=right?.35:-.35,y=-.45+(n%3)*.4;return <circle key={n} cx={Number(project(x,y,right).split(',')[0])} cy={Number(project(x,y,right).split(',')[1])} r="9" fill="#f1f5ed" stroke={colors.blue} strokeWidth="2"/>});
  return <section className="textbook-workbench" data-textbook-model="paper-fold"><Heading model={props.model}>沿竖直中线对折到180°，再在折好的两层纸上打一孔；展开后追踪对应孔。这里模拟竖直中线的一次对折，可在线下继续试两次对折。</Heading><Board title="围绕中线连续折叠的纸与成对的孔"><polygon points={polygon()} fill="#efc4b2" stroke={colors.red} strokeWidth="2"/>{holes(false)}<polygon points={polygon(true)} fill="#eddcaa" fillOpacity=".88" stroke={colors.gold} strokeWidth="2"/>{holes(true)}<path d={`M${project(0,-.7)}L${project(0,.7)}`} stroke={colors.blue} strokeWidth="3" strokeDasharray="7 5"/><text x="320" y="285" textAnchor="middle" fill={colors.ink}>折痕不动，右半纸绕折痕翻过去。</text></Board><div className="textbook-controls"><label>折叠角度<input type="range" aria-label="纸张对折程度" min="0" max="180" value={angle} onChange={e=>act('fold-paper',{angle:Number(e.target.value)})}/></label><button onClick={()=>act('fold-paper',{angle:180})}>完全对折</button><button onClick={()=>{if(angle!==180){act('punch',{error:'先完全对折，让孔穿过重叠的两层。'},false);return}if(s.marked!.length<3)act('punch',{marked:[...s.marked!,s.marked!.length]})}}>穿透两层打一孔</button><button onClick={()=>act('fold-paper',{angle:0})}>完全展开</button></div><Feedback error={s.error}>已经打{s.marked!.length}次孔；{angle===180?'现在两层重叠，成对的孔也重合。':`展开后可追踪${s.marked!.length*2}个对应孔，它们到折痕的距离相等。`}</Feedback>{toolbar}</section>;
 }
 const x=s.left!,y=s.top!,r=s.rotation!,rad=r*Math.PI/180,tip={x:x+Math.sin(rad)*90,y:y-Math.cos(rad)*90};
 return <section className="textbook-workbench" data-textbook-model="motion"><Heading model={props.model}>拖尾端移动整支箭头；拖箭头尖改变朝向。原来的虚线箭头留在原处，方便对照位置与朝向。</Heading><Board title="可平移、可绕尾端旋转的箭头" height={360}><defs><pattern id="motion-grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="#cee0d8"/></pattern></defs><rect width="640" height="360" fill="url(#motion-grid)"/><path d="M150 190V100M130 120L150 100L170 120" fill="none" stroke={colors.blue} strokeOpacity=".22" strokeWidth="9"/><g transform={`translate(${x} ${y}) rotate(${r})`}><path d="M0 0V-90M-20-70L0-90L20-70" fill="none" stroke={colors.blue} strokeWidth="9" strokeLinecap="round"/></g><DragPoint x={x} y={y} label="拖箭头尾端平移" onMove={(a,b,gestureId)=>act('translate',{left:clamp(a,110,530),top:clamp(b,110,240)},true,gestureId)}/><DragPoint x={tip.x} y={tip.y} label="拖箭头尖旋转" onMove={(a,b,gestureId)=>act('rotate',{rotation:clamp((Math.atan2(a-x,y-b)*180/Math.PI+360)%360,0,359)},true,gestureId)}/></Board><div className="textbook-controls"><button onClick={()=>act('translate',{left:clamp(x+50,110,530)})}>向右平移两格</button><button onClick={()=>act('rotate',{rotation:(r+90)%360})}>绕尾端转90°</button></div><Feedback error={s.error}>尾端位置（{x}，{y}），朝向{r}°。平移改变位置；整支箭头的长度始终不变。</Feedback>{toolbar}</section>;
}
