import {useRef,type ReactNode,type DragEvent,type PointerEvent} from 'react';
export const colors={ink:'#294b53',blue:'#527eab',green:'#469684',red:'#df6c4f',gold:'#e9b44d'};
export function Board({title,children,height=320}:{title:string;children:ReactNode;height?:number}){return <svg className="textbook-board" viewBox={`0 0 640 ${height}`} role="group" aria-label={title}><title>{title}</title><rect width="640" height={height} rx="16" fill="#f1f5ed"/>{children}</svg>}
export function pointerPosition(e:PointerEvent<SVGElement>){const svg=e.currentTarget.ownerSVGElement??e.currentTarget as SVGSVGElement,point=svg.createSVGPoint();point.x=e.clientX;point.y=e.clientY;return point.matrixTransform(svg.getScreenCTM()!.inverse())}
export function DragPoint({x,y,label,onMove,step=5}:{x:number;y:number;label:string;step?:number;onMove:(x:number,y:number)=>void}){
 const dragging=useRef(false);
 return <circle className="textbook-drag-point" role="slider" tabIndex={0} aria-label={label} aria-valuemin={0} aria-valuemax={640} aria-valuenow={Math.round(x)} aria-valuetext={`${Math.round(x)},${Math.round(y)}`} cx={x} cy={y} r="13" fill={colors.gold} stroke={colors.ink} strokeWidth="3" onPointerDown={e=>{dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(dragging.current){const p=pointerPosition(e);onMove(p.x,p.y)}}} onPointerUp={()=>{dragging.current=false}} onPointerCancel={()=>{dragging.current=false}} onKeyDown={e=>{const d:{[key:string]:number[]}={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]};if(d[e.key]){e.preventDefault();onMove(x+d[e.key][0],y+d[e.key][1])}}}/>;
}
export function Token({label,code,children,onClick,disabled=false}:{label:string;code:string;children?:ReactNode;onClick?:()=>void;disabled?:boolean}){return <button className="textbook-token" draggable={!disabled} disabled={disabled} onDragStart={e=>e.dataTransfer.setData('text/plain',code)} onClick={onClick} aria-label={label}>{children??label}</button>}
export function dropCode(e:DragEvent<Element>){e.preventDefault();return e.dataTransfer.getData('text/plain')}
export const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,Math.round(n)));
export function Heading({model,children}:{model:{title:string};children:ReactNode}){return <header className="textbook-heading"><span>动手实验</span><h3>{model.title}</h3><p>{children}</p></header>}
export function Feedback({error,children}:{error?:string;children?:ReactNode}){return <div className={error?'textbook-feedback again':'textbook-feedback'} role="status">{error||children}</div>}
