import type {TextbookModel} from '../../../shared/textbook-models.mjs';
import type {WidgetState} from '../types';
import {useTextbook} from './useTextbook';
import {Board,Token,dropCode,Heading,Feedback,colors} from './Primitives';
export default function SymbolWorkbench(props:{model:TextbookModel;sceneId:string;value:WidgetState;onChange:(s:WidgetState)=>void}){
 const {model}=props,{state:s,act,toolbar,measured:m}=useTextbook(model,props.sceneId,props.value,props.onChange);
 if(model.type==='outfits'){
  const shirt=s.shirt!,pants=s.pants!,code=shirt*model.pants!+pants,add=()=>{if(s.marked!.includes(code)){act('add-outfit',{error:'这一套已经在表里了。重复列一次，不会增加一种新搭配。'},false);return}act('add-outfit',{marked:[...s.marked!,code]})};
  return <section className="textbook-workbench" data-textbook-model="outfits"><Heading model={model}>把一件上衣和一条裤子拖到试衣区，再把这套登记在表里。先固定上衣，逐条换裤子，检查不重不漏。</Heading><div className="outfit-trays">{[0,1].map(i=><Token key={'s'+i} code={`shirt:${i}`} label={`选上衣${i?'B':'A'}`} onClick={()=>act('choose-shirt',{shirt:i})}><svg viewBox="0 0 90 80" aria-hidden="true"><path d="M25 8L6 28L18 41L27 34V70H63V34L72 41L84 28L65 8Q45 22 25 8Z" fill={i?colors.red:colors.blue}/></svg><span>上衣{i?'B':'A'}</span></Token>)}{[0,1,2].map(i=><Token key={'p'+i} code={`pants:${i}`} label={`选裤子${i+1}`} onClick={()=>act('choose-pants',{pants:i})}><svg viewBox="0 0 70 80" aria-hidden="true"><path d="M14 8H56L64 71H39L35 30L31 71H6Z" fill={[colors.green,colors.gold,colors.blue][i]}/></svg><span>裤子{i+1}</span></Token>)}</div><div className="outfit-current textbook-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{const code=dropCode(e);if(/^shirt:[01]$/.test(code))act('choose-shirt',{shirt:Number(code.at(-1))});if(/^pants:[0-2]$/.test(code))act('choose-pants',{pants:Number(code.at(-1))})}}><b>试衣区：上衣{shirt?'B':'A'} ＋ 裤子{pants+1}</b><button onClick={add}>登记这套搭配</button></div><table className="textbook-table"><caption>每一格对应一件上衣和一条裤子</caption><thead><tr><th>上衣／裤子</th>{[1,2,3].map(i=><th key={i}>{i}</th>)}</tr></thead><tbody>{[0,1].map(a=><tr key={a}><th>{a?'B':'A'}</th>{[0,1,2].map(b=><td key={b}>{s.marked!.includes(a*3+b)?'已登记':'空着'}</td>)}</tr>)}</tbody></table><Feedback error={s.error}>目前登记{m.count}套，表里还有{m.total-m.count}个空格。每次各选一样，每个有序组合只计一次。</Feedback>{toolbar}</section>;
 }
 if(model.type==='coding'){
  const add=()=>{if(s.marked!.includes(m.address)){act('register-code',{error:'这个位置已经登记过。不能给同一格重复登记两个身份。'},false);return}act('register-code',{marked:[...s.marked!,m.address]})};
  return <section className="textbook-workbench" data-textbook-model="coding"><Heading model={model}>每段固定表示架、层、格。改字段后，黄色位置随编号移动；数字在这里表示地址，不是物品数量。</Heading><div className="code-fields">{['架号','层号','格号'].map((label,i)=><label key={label}>{label}<select aria-label={label} value={s.alloc![i]} onChange={e=>{const a=[...s.alloc!];a[i]=Number(e.target.value);act('change-address',{alloc:a})}}>{Array.from({length:model.limits![i]},(_,n)=><option key={n}>{n+1}</option>)}</select></label>)}<label>每段位数<select aria-label="编码每段位数" value={s.width} onChange={e=>act('change-width',{width:Number(e.target.value)})}>{[1,2,3].map(i=><option key={i}>{i}</option>)}</select></label><button onClick={()=>act('toggle-separator',{show:!s.show})}>{s.show?'试试去掉分隔符':'加回分隔符'}</button></div><p className="textbook-code" aria-live="polite">{m.code}</p><Board title={`第${s.alloc![0]}架，黄色表示第${s.alloc![1]}层第${s.alloc![2]}格`} height={300}>{Array.from({length:32},(_,i)=>{const row=Math.floor(i/8)+1,col=i%8+1,selected=row===s.alloc![1]&&col===s.alloc![2];return <g key={i} role="button" tabIndex={0} aria-label={`定位第${row}层第${col}格`} onClick={()=>act('change-address',{alloc:[s.alloc![0],row,col]})} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();act('change-address',{alloc:[s.alloc![0],row,col]})}}}><rect x={75+(col-1)*60} y={30+(row-1)*55} width="60" height="55" fill={selected?colors.gold:'#eadfc5'} stroke="#ae8250" strokeWidth="3"/><text x={105+(col-1)*60} y={65+(row-1)*55} textAnchor="middle" fontSize="15" fill={colors.ink}>{String(col).padStart(s.width!,'0')}</text></g>})}<text x="320" y="281" textAnchor="middle" fill={colors.ink}>当前架号{s.alloc![0]} · 4层 · 每层8格</text></Board><div className="textbook-controls"><button onClick={add}>为这个位置登记编号</button><button onClick={()=>{const other=[s.alloc![0]===1?2:1,s.alloc![1],s.alloc![2]];act('test-missing-field',{error:`只写格号${s.alloc![2]}，第${s.alloc![0]}架和第${other[0]}架都可能符合；还要知道架号、层号。`},false)}}>试试只写格号</button></div><Feedback error={s.error}>已登记{s.marked!.length}个位置。{s.width===1?'当前架层格均为一位数，这次连写仍能按固定长度解码；容量扩大时要重新检查。':'前导0保留了每一段的固定长度，不能随意删掉。'}</Feedback>{toolbar}</section>;
 }
 const digits=s.alloc!,set=(i:number,n:number)=>{if(!Number.isInteger(n)||n<0||n>9||(i===0&&n>4)){act('place-digit',{error:'此米尺实验的整数位最多4米，其他位可放0至9。'},false);return}const next=[...digits];next[i]=n;act('place-digit',{alloc:next})},cm=m.cm;
 return <section className="textbook-workbench" data-textbook-model="decimal"><Heading model={model}>数字卡可以放在米、分米、厘米的位置。数字相同，放的位置不同，实际长度也不同。米尺、单位与小数来自同一组数位。</Heading><div className="decimal-tray">{Array.from({length:10},(_,n)=><Token key={n} label={`数字${n}`} code={`digit:${n}`} onClick={()=>act('choose-digit',{choice:n})}>{n}</Token>)}</div><div className="decimal-places">{['米／个位','分米／十分位','厘米／百分位'].map((label,i)=><article className="textbook-dropzone" key={label} onDragOver={e=>e.preventDefault()} onDrop={e=>{const code=dropCode(e);if(/^digit:[0-9]$/.test(code))set(i,Number(code.at(-1)))}}><span>{label}</span><strong>{digits[i]}</strong><button onClick={()=>set(i,s.choice??0)}>放入选中的数字</button></article>)}</div><Board title={`同一长度${cm}厘米在米尺上的位置`} height={220}><path d="M70 130H570" stroke={colors.ink} strokeWidth="3"/>{Array.from({length:6},(_,i)=><g key={i}><line x1={70+i*100} x2={70+i*100} y1="122" y2="144" stroke={colors.ink} strokeWidth="2"/><text x={70+i*100} y="175" textAnchor="middle" fill={colors.ink}>{i}米</text></g>)}<rect x="70" y="70" width={cm} height="24" rx="4" fill={colors.blue}/><path d={`M${70+cm} 60V145`} stroke={colors.blue} strokeWidth="3"/>{model.reference!==undefined&&<><path d={`M${70+model.reference} 55V145`} stroke={colors.red} strokeWidth="3" strokeDasharray="5 4"/><text x="320" y="33" textAnchor="middle" fill={colors.red}>固定对照：0.85米＝85厘米</text></>}</Board><div className="textbook-controls"><button onClick={()=>act('place-digit',{alloc:[1,3,0]})}>摆1米3分米</button><button onClick={()=>act('place-digit',{alloc:[1,0,3]})}>摆1米3厘米</button></div><Feedback error={s.error}>{digits[0]}.{digits[1]}{digits[2]}米＝{m.dm}分米＝{cm}厘米。{digits[1]===0?'十分位的0表示没有分米，不能删掉后把厘米挪成分米。':''}{model.reference!==undefined?` 与85厘米相比，现在${cm===85?'相等':cm>85?'更长':'更短'}。`:''}</Feedback>{toolbar}</section>;
}
