import type {TextbookModel} from '../../../shared/textbook-models.mjs';
import type {WidgetState} from '../types';
import {useTextbook} from './useTextbook';
import {Board,DragPoint,clamp,Heading,Feedback,colors} from './Primitives';
export default function TimeWorkbench(props:{model:TextbookModel;sceneId:string;value:WidgetState;onChange:(s:WidgetState)=>void}){
 const {model}=props,{state:s,act,toolbar,measured:m}=useTextbook(model,props.sceneId,props.value,props.onChange);
 if(model.type==='calendar')return <section className="textbook-workbench" data-textbook-model="calendar"><Heading model={model}>换年份和月份，重新检查天数与星期位置。选一个日期，再向后走7天，看星期是否相同。</Heading><div className="textbook-controls"><label>年份<input type="number" aria-label="月历年份" min="1900" max="2100" value={s.year} onChange={e=>{const year=Number(e.target.value);if(Number.isInteger(year)&&year>=1900&&year<=2100)act('change-year',{year,marked:[]})}}/></label><label>月份<select aria-label="月历月份" value={s.month} onChange={e=>act('change-month',{month:Number(e.target.value),marked:[]})}>{Array.from({length:12},(_,i)=><option key={i}>{i+1}</option>)}</select></label><button onClick={()=>act('change-year',{year:2023,month:2,marked:[]})}>2023年2月</button><button onClick={()=>act('change-year',{year:2024,month:2,marked:[]})}>2024年2月</button></div><div className="interactive-calendar" role="group" aria-label={`${s.year}年${s.month}月，${m.days}天`}><h4>{s.year}年{s.month}月</h4><div>{['一','二','三','四','五','六','日'].map(day=><b key={day}>星期{day}</b>)}{Array.from({length:m.offset},(_,i)=><span key={'empty'+i}/>)}{Array.from({length:m.days},(_,i)=><button key={i} aria-pressed={s.marked!.includes(i+1)} onClick={()=>act('select-date',{marked:[i+1]})}>{i+1}</button>)}</div></div><div className="textbook-controls"><button disabled={!s.marked!.length||s.marked![0]+7>m.days} onClick={()=>act('move-seven-days',{marked:[s.marked![0]+7]})}>选中的日期向后7天</button></div><Feedback error={s.error}>{s.year}年是{m.leap?'闰年':'平年'}，本月{m.days}天。{s.marked!.length?`选中${s.marked![0]}日，是星期${['一','二','三','四','五','六','日'][(m.offset+s.marked![0]-1)%7]}。`:''}同一张30天表不能代表所有月份。</Feedback>{toolbar}</section>;
 const time=s.minutes!,minute=time%60,hour=(time/60)%12,hp={x:180+63*Math.sin(hour*Math.PI/6),y:155-63*Math.cos(hour*Math.PI/6)},mp={x:180+92*Math.sin(minute*Math.PI/30),y:155-92*Math.cos(minute*Math.PI/30)},format=(t:number)=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;
 const moveHand=(x:number,y:number)=>{const newMinute=Math.round(((Math.atan2(x-180,155-y)*180/Math.PI+360)%360)/6)%60;let delta=newMinute-minute;if(delta>30)delta-=60;if(delta<-30)delta+=60;act('move-minute-hand',{minutes:clamp(time+delta,0,1440)})};
 return <section className="textbook-workbench" data-textbook-model="clock"><Heading model={model}>金色点是分针端点。拖分针走过16:00，再走到16:05；下方时间轴记录同一天的时刻，经过多久从起点数。</Heading><Board title="可以拖动分针与24小时时间轴的钟面" height={385}><circle cx="180" cy="155" r="114" fill="#fffaf0" stroke={colors.blue} strokeWidth="5"/>{Array.from({length:12},(_,i)=>{const a=(i+1)*Math.PI/6;return <text key={i} x={180+96*Math.sin(a)} y={162-96*Math.cos(a)} textAnchor="middle" fill={colors.ink}>{i+1}</text>})}<line x1="180" y1="155" x2={hp.x} y2={hp.y} stroke={colors.blue} strokeWidth="8" strokeLinecap="round"/><line x1="180" y1="155" x2={mp.x} y2={mp.y} stroke={colors.red} strokeWidth="5"/><DragPoint x={mp.x} y={mp.y} label="拖动分针前进或后退" onMove={moveHand}/><text x="450" y="137" textAnchor="middle" fill={colors.ink} fontSize="35">{format(time)}</text><text x="450" y="174" textAnchor="middle" fill={colors.ink}>目标：16:05</text><path d="M60 321H580" stroke={colors.blue} strokeWidth="4"/>{[0,6,12,18,24].map(h=><g key={h}><line x1={60+h/24*520} x2={60+h/24*520} y1="311" y2="333" stroke={colors.ink}/><text x={60+h/24*520} y="363" textAnchor="middle" fill={colors.ink}>{h}:00</text></g>)}<circle cx={60+model.start!/1440*520} cy="321" r="6" fill={colors.green}/><DragPoint x={60+time/1440*520} y={321} label="拖24小时轴上的时刻" onMove={x=>act('move-timeline',{minutes:clamp((x-60)/520*1440,0,1440)})}/></Board><div className="textbook-controls"><button onClick={()=>act('advance-minute',{minutes:Math.min(1440,time+1)})}>向前1分钟</button><button onClick={()=>act('advance-minute',{minutes:Math.min(1440,time+5)})}>向前5分钟</button><button onClick={()=>act('advance-minute',{minutes:Math.min(1440,time+40)})}>向前40分钟</button></div><Feedback error={s.error}>起点15:20，现在{format(time)}，{m.elapsed>=0?`经过${m.elapsed}分钟`:`比起点早${-m.elapsed}分钟`}。{m.reached?'到16:00先经过40分钟，再到16:05经过5分钟，共45分钟。':'时刻是时间轴上的位置；经过的分钟是一段长度。'}</Feedback>{toolbar}</section>;
}
