import {useEffect,useState} from 'react';
import type {Progress} from '../types';
import type {Task,TaskResult,SelfCheckRecord} from '../studio/types';
type Row={sessionId:string;revision:number;lessonId:string;assessment?:string;task:Task;result:TaskResult;selfCheck:SelfCheckRecord;help:string|null;history:{comment:string;at:string;verdict:string}[]};
async function request(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const out=await r.json();if(!r.ok)throw Error(out.error);return out;}
export default function ParentFormalReview({onProgress}:{onProgress:(p:Progress)=>void}){
 const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState(''),[comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const out=await request('/api/parent/formal');setRows(out.tasks);};
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const row=rows.find(r=>`${r.sessionId}:${r.task.id}`===selected);
 const grade=async(verdict:string)=>{if(!row)return;setBusy(true);setError('');try{const out=await request('/api/parent/formal/review',{sessionId:row.sessionId,revision:row.revision,taskId:row.task.id,eventId:crypto.randomUUID(),verdict,comment});onProgress(out.progress);await load();setComment('');}catch(e){setError(e instanceof Error?e.message:'没有保存，请重新核对');}finally{setBusy(false)}};
 return <section className="parent-formal-review"><h3>正式练习中的解释题</h3><p>核对首答、订正、提示和解释。人工批阅只确认这道题，不自动发积分，也不直接代表延迟掌握。</p><button onClick={()=>void load().catch(e=>setError(e.message))}>刷新解释题队列</button><label>选择作答<select value={selected} onChange={e=>{setSelected(e.target.value);setComment('')}}><option value="">请选择（{rows.length}条）</option>{rows.map(r=><option key={`${r.sessionId}:${r.task.id}`} value={`${r.sessionId}:${r.task.id}`}>{r.lessonId} · {r.task.id.split('-').at(-1)} · {r.result.status==='pendingReview'?'待核对':'可更正'}</option>)}</select></label>{row&&<><h4>{row.task.prompt}</h4><p>来源：{row.assessment?'撤教具五题小测':'正式练习'}；{row.help?'使用过辅助：'+row.help:'无页面辅助记录；请核对线下帮助'}</p><blockquote>首答：{row.selfCheck?.firstAnswer?.value}<br/>最终解释：{row.result.finalAnswer?.value}</blockquote><p>自查：{row.selfCheck?.evidence?.reflection}</p><details><summary>家长参考（请对照推理，不只看结论）</summary><p>{row.task.solution}</p><p>{row.task.expected}</p></details><label>给Kevin的核对反馈<textarea value={comment} maxLength={1200} onChange={e=>setComment(e.target.value)}/></label><div className="thinking-help"><button disabled={busy||comment.trim().length<2} onClick={()=>void grade('correct')}>关系与解释正确</button><button disabled={busy||comment.trim().length<2} onClick={()=>void grade('needs-remediation')}>需要回补</button></div><details><summary>更正历史（{row.history.length}条）</summary>{row.history.map((h,i)=><p key={i}>{h.at} · {h.verdict} · {h.comment}</p>)}</details></>}{error&&<p role="alert">{error}<button onClick={()=>void load().catch(e=>setError(e.message))}>载入最新记录（保留反馈文字）</button></p>}</section>;
}
