import {useState} from 'react';
import type {Data,ThinkingCard,ThinkingRecord,Progress} from '../types';
import {api} from '../api';
import ThinkingFigure from './ThinkingFigure';
import './thinking.css';
const checks=['重新读条件：数量、单位和范围有没有遗漏？','用图、算式或列举检查自己的推理，必要时代回原条件。','答案是否找全、有没有重复？能用自己的话说明为什么吗？'];
export default function ThinkingPanel({card,data,onProgress,onBack,onBase}:{card:ThinkingCard;data:Data;onProgress:(p:Progress)=>void;onBack:()=>void;onBase:()=>void}){
 const [record,setRecord]=useState<ThinkingRecord|undefined>(data.progress.studio?.thinking?.[card.id]),[answer,setAnswer]=useState(record?.firstAnswer??''),[final,setFinal]=useState(record?.finalAnswer??record?.firstAnswer??''),[reflection,setReflection]=useState(record?.reflection??''),[ticks,setTicks]=useState(record?.checks??[false,false,false]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const send=async(action:string,extra:Record<string,unknown>={})=>{setBusy(true);setError('');try{const out=await api.thinking({taskId:card.id,eventId:crypto.randomUUID(),revision:record?.revision??0,action,...extra});setRecord(out.result.record);onProgress(out.progress);return true}catch(e){setError(e instanceof Error?e.message:'没有保存成功。');return false}finally{setBusy(false)}};
 const first=record?.firstAnswer!==null&&record?.firstAnswer!==undefined;
 return <section className="thinking-panel"><button onClick={onBack}>← 回到本章主线</button><header><small>本章直接提升 · 可选 · {card.minutes}分钟</small><h2>{card.title}</h2><p>{card.bridgeFromCore}</p></header><ThinkingFigure card={card}/><div className="thinking-question"><h3>换个情境，试着自己解决</h3><p>{card.question}</p><small>你可以画在纸上，再把答案和理由写下来。不会也可以保存真实的想法。</small></div><section><h3>1 · 留下第一次想法</h3>{first?<blockquote>{record.firstAnswer}<small>已保留首答 · {record.firstAssisted?'答题前用过辅助':'答题前未查看辅助'}</small></blockquote>:<><label>我的首答和理由<textarea maxLength={1200} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="我认为……因为……"/></label><button disabled={busy||!answer.trim()} onClick={()=>{setFinal(answer);void send('first',{answer})}}>保存首答，再自查</button></>}</section>{first&&<section><h3>2 · 自己检查</h3><div>{checks.map((t,i)=><label className="thinking-check" key={t}><input type="checkbox" disabled={record?.phase!=='first'} checked={ticks[i]} onChange={e=>setTicks(ticks.map((v,n)=>n===i?e.target.checked:v))}/>{t}</label>)}</div><label>检查时发现什么？哪一步最关键？<textarea maxLength={600} disabled={record?.phase!=='first'} value={reflection} onChange={e=>setReflection(e.target.value)}/></label>{record?.phase==='first'&&<button disabled={busy||!ticks.every(Boolean)||reflection.trim().length<2} onClick={()=>void send('check',{checks:ticks,reflection})}>保存自查证据</button>}</section>}{record?.phase&&record.phase!=='first'&&<section><h3>3 · 最终答案与解释</h3><label>检查后的答案<textarea maxLength={1200} disabled={record.phase==='pendingReview'} value={final} onChange={e=>setFinal(e.target.value)}/></label>{record.phase==='self-checked'?<button disabled={busy||!final.trim()} onClick={()=>void send('final',{answer:final})}>提交，交给家长核对</button>:<p role="status">已保存，等待家长核对解释。首答、自查和辅助记录都已保留；提交不会自动计为答对或增加积分。</p>}</section>}<aside><h3>需要一点帮助时</h3><div className="thinking-help">{[1,2].map(level=><button disabled={busy} key={level} onClick={()=>void send('hint',{level})}>{level===1?'一点提示':'再给一个提示'}</button>)}<button disabled={busy||!first} onClick={()=>void send('solution')}>看参考解释</button><button disabled={busy} onClick={async()=>{if(await send('reference'))onBase()}}>回看本章基础</button></div>{record?.help.map(h=><p className="thinking-revealed" key={h.kind+h.level}><b>{h.kind==='hint'?`提示${h.level}`:h.kind==='solution'?'参考解释':'回看记录'}</b><br/>{h.text}<small className="thinking-help-time">查看时间：{new Date(h.at).toLocaleString('zh-CN',{hour12:false})}</small></p>)}<p>使用提示是学习的一部分；系统会记录使用时间，并与独立作答分开。</p></aside>{error&&<p role="alert">{error}</p>}<details><summary>家长核对依据与适用范围</summary><p>{card.applicability}</p><p>需要Kevin讲清：{card.thinkingEvidence}</p><p>本卡是原有题库的迁移练习，不另加一节必修课。正式间隔复习沿教材课程按1、3、7、21天安排；本卡目前保留待核对证据。</p></details></section>;
}
