import type {Progress} from './types';
import type {PilotLesson,PilotSession} from './studio/types';
import {lessonEvidence} from '../shared/learning-evidence.mjs';
const answerText=(answer:Record<string,string>|undefined)=>Object.entries(answer??{}).filter(([key])=>!key.startsWith('check')&&!key.endsWith('Unit')).map(([key,value])=>`${key==='value'?'答案':key}：${value}`).join('；');
export default function LearningEvidencePanel({progress,lessons}:{progress:Progress;lessons:PilotLesson[]}){
  const rows=lessons.map(lesson=>({lesson,evidence:lessonEvidence(progress,lesson.lessonId,lesson.contentVersion)})).filter(row=>row.evidence.status!=='new');
  const pending=(Object.values(progress.studio?.sessions??{}) as PilotSession[]).flatMap(session=>session.tasks.filter(t=>session.results[t.id]?.status==='pendingReview').map(task=>({session,task,result:session.results[task.id]}))).sort((a,b)=>Date.parse(b.result.at)-Date.parse(a.result.at));
  return <section className="parent-panel learning-evidence-panel"><header><div><h3>学习证据</h3><p>独立达标要求：新迁移题首答正确、无帮助，以及至少隔一天的到期复习。核心最终做对表示已练习。</p></div></header><div className="evidence-summary"><span>已探索 {rows.filter(r=>r.evidence.explored).length}</span><span>已练习 {rows.filter(r=>r.evidence.practiced).length}</span><span>独立达标 {rows.filter(r=>r.evidence.independent).length}</span><span>自己订正 {rows.reduce((n,r)=>n+r.evidence.selfCorrections,0)}</span></div>{rows.slice(0,12).map(({lesson,evidence})=><details key={lesson.lessonId}><summary>{lesson.shortTitle} · {evidence.independent?'独立达标':evidence.practiced?'已练习':'已探索'}</summary><p>无帮助迁移：{evidence.transfer}组；独立延迟复习：{evidence.retained}次；自己订正：{evidence.selfCorrections}题；解释待核对：{evidence.pending}题。</p></details>)}{pending.length>0&&<><h4>解释题待核对 · {pending.length}题</h4><p>文字回答保留原话。核对结论是否回答问题、关键关系是否成立，以及能否解释理由；这些回答未计入自动答对和积分。</p>{pending.slice(0,10).map(({session,task,result})=><details key={`${session.id}:${task.id}`}><summary>{task.prompt}</summary><p><b>首答：</b>{answerText(result.firstAnswer)}</p><p><b>终答：</b>{answerText(result.finalAnswer)}</p><p><b>自查记录：</b>{result.selfCheckEvidence?.reflection??'旧版本没有记录具体检查动作'}</p><p><b>参考过程：</b>{result.solution??task.solution??'打开课程对照例题'}</p><p>{result.assisted?'过程中使用过帮助':'没有打开帮助'} · {result.selfCorrection?'提交前修改过回答':'回答保持原样'}</p></details>)}</>}</section>;
}
