export type Question = {id:string;prompt:string;answer:number;unit:string;choices?:string[];hints:string[];explanation:string;misconception:string;level?:'warmup'|'core'|'transfer'|'challenge';representation?:string;exerciseType?:'numeric'|'choice'};
export type Lesson = {id:string;grade?:number;world:string;title:string;subtitle:string;kind:'foundation'|'thinking';minutes:number;concept:string;origin?:string;mathIdea?:string;whyQuestion?:string;humanNeed?:string;invention?:string;essence?:string;extensionChain?:string[];retellPrompt?:string;birthStories?:{name:string;problem:string;tool:string}[];practiceCount?:number;lessonFlow?:string[];representations?:string[];learningCycle?:string;assessment?:string[];strand?:string;gradeBand?:string;prerequisites:string[];thinkingSkills:string[];story:string;discovery:string;steps:string[];takeaway:string;lab:string;labConfig:Record<string,any>;sourceRefs?:string[];questions:Question[]};
export type Attempt = {id:string;lessonId:string;questionId:string;prompt:string;answer:number;expected:number;correct:boolean;usedHint:boolean;mode:string;at:string;misconception:string;explanation:string};
export type Review = {dueAt:string;stage:number;lastReviewedAt:string|null;successDates:string[];mistakes:string[]};
export type PetFriend = {growth:number;bond:number;meals:number;joinedAt:string;gifts:number[]};
export type PetMemory = {pet:string;kind:string;text:string;at:string;lessonId:string|null};
export type PetCare = {version:1;friends:Record<string,PetFriend>;scene:string;decorations:string[];daily:{day:string;touches:number;plays:number};claims:string[];receipts:{id:string;action:string;result:Record<string,unknown>}[];memories:PetMemory[]};
export type PetMission = {id:string;name:string;detail:string;done:boolean;item:string;amount:number;route:string;claimed:boolean};
export type Progress = {schemaVersion:number;profile:{name:string;grade:number;selectedGrade?:number;textbook:string};settings:{sound:boolean;dailyMinutes:number;reviewDays:number[]};attempts:Attempt[];lessons:Record<string,{solved:string[];completedAt:string|null;lastQuestionId?:string;retells?:{id:string;text:string;at:string}[]}>;reviews:Record<string,Review>;wallet:{coins:number;earned:number;spent:number;ledger:{id:string;amount:number;label:string;at:string}[]};pets:{owned:string[];active:string;xp:number;feedCount:number;accessory:string|null;care:PetCare};inventory:Record<string,number>;studio?:{version:number;reading:Record<string,unknown>;sessions:Record<string,unknown>;notes:unknown[];events:unknown[];entitlements:Record<string,number>;daily:Record<string,{tasks:number;completion:number}>;thinking?:Record<string,ThinkingRecord>;review?:Record<string,unknown>}};
export type Data = {progress:Progress;courses:Lesson[];articleCourses?:PilotLesson[];thinkingCards?:ThinkingCard[];serverTime:string;catalogVersion:string};
import type {PilotLesson} from './studio/types';

export type ThinkingCard={id:string;title:string;originUnit:string;parentLessonId:string;thinkingDomain:string;thinkingLabel:string;classification:string;releaseBucket:'direct'|'bridge'|'deferred';publicationStatus:'guided-study'|'prepared-not-published';releaseReason:string;recommended:boolean;minutes:string|number;bridgeFromCore:string;question?:string;contentVersion:string;scoring:'adult_review'};
export type ScaffoldEvidence={usedManipulative:boolean;usedAnswerValidation:boolean;validationAttempts:number;matchedAttempts:number;withVisualScaffold:boolean;legacyEstimate?:boolean};
export type ThinkingRecord={seenVariantIds?:string[];recordSchemaVersion?:number;mode?:"explore"|"challenge";scaffold?:ScaffoldEvidence;firstScaffold?:ScaffoldEvidence;submittedScaffold?:ScaffoldEvidence;postReviewStudy?:{kind:string;level:number;text:string;at:string;stage:string}[];taskId:string;contentVersion:string;revision:number;phase:'first'|'self-checked'|'pendingReview'|'reviewed';firstAnswer:string|null;firstAt?:string;firstAssisted?:boolean;help:{kind:'hint'|'solution'|'reference';level:number;text:string;at:string;stage?:'before-first'|'after-first'|'after-submission'}[];checks?:boolean[];reflection?:string;finalAnswer?:string;submittedAt?:string;savedAt:string;status?:'pendingReview'|'reviewed';variantIndex?:number;variant?:{id:string;index:number;question:string;conditions:string[];figure:{unit:string;values:number[]}};tool?:{version:string;values:number[];view:number};toolHistory?:{command:string;before:{version:string;values:number[];view:number};after:{version:string;values:number[];view:number};at:string;stage:string}[];attemptId?:string;reviews?:ThinkingReview[];attempts?:ThinkingRecord[];review?:{verdict:string;stage:number;completed:boolean;strongEvidence?:boolean;dueAt:string|null;anchorAt:string}};
export type ThinkingReview={verdict:string;comment:string;reviewer:string;source:string;at:string;causes:string[];helpCount:number;evidence?:{scaffold:ScaffoldEvidence;mode:string;firstAnswer:string;finalAnswer:string;reflection:string}};
export type ParentThinkingCard={id:string;title:string;question:string;answer:string;reason:string;solutionSteps:string[];applicability:string;thinkingEvidence:string;record:ThinkingRecord;variant?:{question:string;answer:string;reason:string;conditions:string[]}|null};
