import {ChevronRight} from 'lucide-react';
import type {Data} from './types';
import {learningReviews,type LearningEntry,type OpenLearning} from './learningMap';
import type {PilotSession,ReadingRecord} from './studio/types';
const labels={foundation:'课本主线',enhancement:'本章提升',olympiad:'数学思想'};
const statuses={new:'还没开始',explored:'已浏览',practiced:'已练习',independent:'独立迁移与复习达标'};
export default function UnitLearningMap({data,entries,onOpen,onThinking}:{data:Data;entries:LearningEntry[];onOpen:OpenLearning;onThinking:(id:string)=>void}){
  const groups=new Map<string,LearningEntry[]>();
  for(const entry of entries){const id=entry.source==='article'?entry.lesson.textbookUnit?.id??'bridges':'bridges';groups.set(id,[...(groups.get(id)??[]),entry]);}
  const latest=(Object.values(data.progress.studio?.sessions??{}) as PilotSession[]).sort((a,b)=>Date.parse(b.savedAt)-Date.parse(a.savedAt))[0];
  const recent=[...Object.entries((data.progress.studio?.reading??{}) as Record<string,ReadingRecord>).map(([id,r])=>({id,savedAt:r.savedAt})),...(latest?[{id:latest.lessonId,savedAt:latest.savedAt}]:[])].filter(item=>entries.some(entry=>entry.id===item.id)).sort((a,b)=>Date.parse(b.savedAt)-Date.parse(a.savedAt))[0];
  const current=entries.find(e=>e.id===recent?.id),currentUnit=current?.source==='article'?current.lesson.textbookUnit?.id??'bridges':'G3-U02';
  const due=learningReviews(data).filter(row=>Date.parse(row.review.dueAt)<=Date.now());
 const thinkingDue=Object.values(data.progress.studio?.thinking??{}).filter(r=>r.review?.dueAt&&Date.parse(r.review.dueAt)<=Date.now()&&r.phase==='reviewed');
  return <div className="textbook-unit-map">{thinkingDue.length>0&&<section className="parent-panel"><h3>到期的思维迁移复习</h3>{thinkingDue.map(r=><button key={r.taskId} onClick={()=>onThinking(r.taskId)}>{data.thinkingCards?.find(t=>t.id===r.taskId)?.title??r.taskId} · 换情境再试</button>)}</section>}{[...groups].map(([id,rows])=>{
    const first=rows.find(e=>e.source==='article'),unit=first?.source==='article'?first.lesson.textbookUnit:undefined,cards=(data.thinkingCards??[]).filter(t=>t.originUnit===id),recommended=cards.find(t=>t.recommended),unitDue=due.filter(r=>rows.some(e=>e.id===r.entry.id));
    return <details className="textbook-unit" key={id} open={id===currentUnit||entries.length<15}><summary><div><small>{unit?(unit.term==='upper'?'三年级上册':'三年级下册'):'回补与数学桥梁'}{unit?` · 参考教材印刷页 ${unit.printedPages}`:''}</small><h3>{unit?.title??'数的现实起点与数学思想'}</h3><p>{rows.filter(e=>e.track==='foundation').length}节基础 · {rows.filter(e=>e.track==='enhancement').length}节提升 · {rows.filter(e=>e.track==='olympiad').length}节思想{unitDue.length?` · ${unitDue.length}节到期复习`:''}</p></div><ChevronRight/></summary><div className="unit-learning-content"><p className="unit-path-note">先沿课本主线理解问题，再选本章提升或数学思想。各章可自由进入；提升是选学，不挡住下一章。练习后按1、3、7、21天换情境复习。</p>{(['foundation','enhancement','olympiad'] as const).map(track=>{const tracks=rows.filter(e=>e.track===track);return <section className={`unit-track track-${track}`} key={track}><h4>{labels[track]}</h4>{tracks.length===0&&<p className="unit-review-empty">{track==='enhancement'?'可选做下面的本章迁移题，从基础关系继续追问。':track==='olympiad'?'本章数学思想收在下方思维库；标为暂缓的内容尚未开放。':'当前筛选没有课本主线课程，可切换到全部查看。'}</p>}{tracks.map(entry=><article key={entry.id}><button onClick={()=>onOpen(entry)}><div><small>{entry.id} · 题库{entry.questionCount}题 · 每次建议3–5题</small><b>{entry.title}</b><span>{entry.evidence?.status==='explored'&&entry.evidence.operationRecorded?'已留操作记录':statuses[entry.evidence?.status??'new']}</span></div><ChevronRight/></button>{entry.source==='article'&&<p className="unit-prerequisites">先会：{entry.lesson.recommendedPrerequisites.join('、')||'从本课故事开始即可'}{entry.lesson.interactionStatus==='static-visual'?' · 本课为图示讲解，尚未提供可操作实验':''}{entry.lesson.editorialStatus==='review-required'?' · 内容待逐题教学审核':''}</p>}</article>)}</section>})}{recommended&&<aside className="unit-transfer-recommendation"><small>本章之后，推荐选做一题</small><h4>{recommended.title}</h4><p>{recommended.bridgeFromCore}</p><button onClick={()=>onThinking(recommended.id)}>试这道迁移题 <ChevronRight/></button></aside>}{cards.length>0&&<details className="unit-thinking-library"><summary>本章思维库 · {cards.filter(t=>t.publicationStatus==='guided-study').length}张已开放 / {cards.length}张已整理</summary>{cards.map(t=><article key={t.id} className={t.publicationStatus==='prepared-not-published'?'prepared-card':''}><small>{t.classification} · {t.thinkingLabel}</small>{t.publicationStatus==='guided-study'?<button onClick={()=>onThinking(t.id)}>{t.title}<ChevronRight/></button>:<><b>{t.title}</b><small>暂缓开放：{t.releaseReason}</small></>}</article>)}</details>}<section className="unit-track"><h4>间隔复习 · 1 / 3 / 7 / 21天</h4>{unitDue.length===0&&<p className="unit-review-empty">本章还没有到期复习。核心练习完成后，会安排新情境的独立复习；现在也可自由回看任意课程。</p>}{unitDue.slice(0,3).map(r=><button key={r.entry.id} onClick={()=>onOpen(r.entry,'review')}>{r.entry.title}<ChevronRight/></button>)}</section></div></details>;
  })}</div>;
}
