import fs from 'node:fs';
const source=JSON.parse(fs.readFileSync(new URL('../course-plan-v2/grade-3-thinking.json',import.meta.url),'utf8'));
const domains={U01:'多视角与信息约束',U02:'运算结构与逆向思考',U03:'测量、重叠与端点',UP01:'等量与不变量',U04:'位值与倍数关系',UP02:'编码与有序枚举',U05:'角的结构与有序计数',U06:'整体、份数与逆推',U07:'搭配与条件筛选',L01:'对称与染色',L02:'余数、枚举与界限',L03:'边界与有序枚举',L04:'面积守恒与分类计数',L05:'数据约束与保证',LP01:'周期与日历',L06:'金额、组合与最优化',L07:'集合与数量关系'};
const methodLabels={
 'reasoning.sufficient-evidence':'信息是否足够','reasoning.exhaustive-cases':'分类与找全','arithmetic.parentheses.model':'括号与现实运算顺序','reasoning.invariant-difference':'差的不变量','reasoning.segment-compensation':'线段取差与补偿','reasoning.intervals':'端点与间隔','reasoning.equal-elimination':'等量操作与消元','reasoning.branching':'分支与排除','arithmetic.law.distribution':'倍数变化与分配结构','reasoning.constrained-enumeration':'按条件枚举','representation.code-ambiguity':'编码的唯一性','reasoning.ordered-choice':'有顺序的选择','reasoning.counterexample':'用参照检验推断','reasoning.systematic-enumeration':'有序枚举','fraction.whole-versus-quantity':'整体、比例与实际量','reasoning.changing-whole':'整体改变后的份数','reasoning.constrained-combinations':'组合与条件筛选','reasoning.path-enumeration':'路线的有序计数','geometry.symmetry-unfold':'展开与对称','reasoning.coloring-invariant':'染色与不变量','reasoning.remainder-range':'商的范围与余数','reasoning.systematic-filter':'逐层筛选','reasoning.fixed-sum-enumeration':'固定和与枚举','reasoning.boundary-compensation':'边界增减与补偿','geometry.equal-area-decomposition':'剪拼与面积守恒','reasoning.count-by-size':'按大小分类计数','reasoning.table-constraints':'统计表约束','reasoning.pigeonhole':'分配与至少保证','reasoning.period-remainder':'周期与余数','reasoning.equalize-pair':'等间隔与中间量','reasoning.decimal-combinations':'小数金额与不重复组合','reasoning.finite-optimization':'有限枚举与最优化','reasoning.inclusion-exclusion':'集合重叠与容斥','reasoning.sum-difference':'和差关系','measurement.overlap':'重叠长度与接头','reasoning.inverse':'逆向思考','reasoning.overcount':'重复计数与扣除','reasoning.cancellation':'共同部分与消去','arithmetic.difference-change':'差的变化','reasoning.ordered-search':'有序寻找','reasoning.optimization':'极值与最优化','reasoning.substitution':'等量替换与归一','reasoning.equivalent-relations':'等量关系与盈亏','reasoning.part-unit':'份数与和倍、差倍','reasoning.remainder-search':'余数约束与筛选','reasoning.cycle':'往返与循环边界','reasoning.transfer-invariant':'转移与差的不变量'};
const bridges=new Set(['G3-U04-S01','G3-U04-S03','G3-U04-S04','G3-U04-S10','G3-U04-S15','G3-U06-S19']);
// First release: exactly one explicitly illustrated/worded transfer per textbook unit.
// Remaining cards retain their original problem and provenance; they are not pretend published lessons.
export const thinkingCards=source.tasks.map(t=>{
 const published=t.id.endsWith('-TH1');
 const bucket=t.layer==='奥数思想选学'||bridges.has(t.id)?'bridge':'direct';
 return {...t,originUnit:t.unitId,thinkingDomain:['G3-U04-S03','G3-U04-S04'].includes(t.id)?'enumeration.extremum':t.conceptId,thinkingLabel:methodLabels[t.conceptId]??domains[t.unitId.replace('G3-','')],classification:bucket==='direct'?'本章直接提升':'数学思想桥梁',releaseBucket:published?bucket:'deferred',publicationStatus:published?'guided-study':'prepared-not-published',releaseReason:published?'本章首张迁移卡已逐题整理；解释由家长核对。':'保留原题与来源，待专用题图、操作及教学核对；不计入已发布课程。',recommended:published,contentVersion:'thinking.2026-10-08.1',scoring:'adult_review'};
});
export const publicThinkingCard=t=>({id:t.id,title:t.title,originUnit:t.originUnit,parentLessonId:t.parentLessonId,thinkingDomain:t.thinkingDomain,thinkingLabel:t.thinkingLabel,classification:t.classification,releaseBucket:t.releaseBucket,publicationStatus:t.publicationStatus,releaseReason:t.releaseReason,recommended:t.recommended,minutes:t.minutes,bridgeFromCore:t.bridgeFromCore,question:t.publicationStatus==='guided-study'?t.question:undefined,applicability:t.publicationStatus==='guided-study'?t.applicability:undefined,thinkingEvidence:t.publicationStatus==='guided-study'?t.thinkingEvidence:undefined,contentVersion:t.contentVersion,scoring:t.scoring});
